// flow-typed signature: 427fa611bd46b5f4492d5355839fbfb8
// flow-typed version: <<STUB>>/@paypal/common-components_v^1.0.35/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/common-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@paypal/common-components" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@paypal/common-components/__sdk__" {
  declare module.exports: any;
}

declare module "@paypal/common-components/dist/ui" {
  declare module.exports: any;
}

declare module "@paypal/common-components/dist/ui.min" {
  declare module.exports: any;
}

declare module "@paypal/common-components/globals" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/config" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/declarations" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/globals" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/interface" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/overlay" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/overlay/style" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/overlay/template" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/three-domain-secure/component" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/three-domain-secure" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/types" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/ui" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/ui/spinner" {
  declare module.exports: any;
}

declare module "@paypal/common-components/src/ui/venmoSpinner" {
  declare module.exports: any;
}

// Filename aliases
declare module "@paypal/common-components/__sdk__.js" {
  declare module.exports: $Exports<"@paypal/common-components/__sdk__">;
}
declare module "@paypal/common-components/dist/ui.js" {
  declare module.exports: $Exports<"@paypal/common-components/dist/ui">;
}
declare module "@paypal/common-components/dist/ui.min.js" {
  declare module.exports: $Exports<"@paypal/common-components/dist/ui.min">;
}
declare module "@paypal/common-components/globals.js" {
  declare module.exports: $Exports<"@paypal/common-components/globals">;
}
declare module "@paypal/common-components/src/config.js" {
  declare module.exports: $Exports<"@paypal/common-components/src/config">;
}
declare module "@paypal/common-components/src/declarations.js" {
  declare module.exports: $Exports<"@paypal/common-components/src/declarations">;
}
declare module "@paypal/common-components/src/globals.js" {
  declare module.exports: $Exports<"@paypal/common-components/src/globals">;
}
declare module "@paypal/common-components/src/index" {
  declare module.exports: $Exports<"@paypal/common-components/src">;
}
declare module "@paypal/common-components/src/index.js" {
  declare module.exports: $Exports<"@paypal/common-components/src">;
}
declare module "@paypal/common-components/src/interface.js" {
  declare module.exports: $Exports<"@paypal/common-components/src/interface">;
}
declare module "@paypal/common-components/src/overlay/index" {
  declare module.exports: $Exports<"@paypal/common-components/src/overlay">;
}
declare module "@paypal/common-components/src/overlay/index.js" {
  declare module.exports: $Exports<"@paypal/common-components/src/overlay">;
}
declare module "@paypal/common-components/src/overlay/style.js" {
  declare module.exports: $Exports<"@paypal/common-components/src/overlay/style">;
}
declare module "@paypal/common-components/src/overlay/template.jsx" {
  declare module.exports: $Exports<"@paypal/common-components/src/overlay/template">;
}
declare module "@paypal/common-components/src/three-domain-secure/component.jsx" {
  declare module.exports: $Exports<"@paypal/common-components/src/three-domain-secure/component">;
}
declare module "@paypal/common-components/src/three-domain-secure/index" {
  declare module.exports: $Exports<"@paypal/common-components/src/three-domain-secure">;
}
declare module "@paypal/common-components/src/three-domain-secure/index.js" {
  declare module.exports: $Exports<"@paypal/common-components/src/three-domain-secure">;
}
declare module "@paypal/common-components/src/types.js" {
  declare module.exports: $Exports<"@paypal/common-components/src/types">;
}
declare module "@paypal/common-components/src/ui/index" {
  declare module.exports: $Exports<"@paypal/common-components/src/ui">;
}
declare module "@paypal/common-components/src/ui/index.js" {
  declare module.exports: $Exports<"@paypal/common-components/src/ui">;
}
declare module "@paypal/common-components/src/ui/spinner.jsx" {
  declare module.exports: $Exports<"@paypal/common-components/src/ui/spinner">;
}
declare module "@paypal/common-components/src/ui/venmoSpinner.jsx" {
  declare module.exports: $Exports<"@paypal/common-components/src/ui/venmoSpinner">;
}
