// flow-typed signature: 6daf3c1d4cd87e14d0400430d3658497
// flow-typed version: <<STUB>>/@paypal/connect-loader-component_v1.1.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/connect-loader-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@paypal/connect-loader-component" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@paypal/connect-loader-component/dist/constants" {
  declare module.exports: any;
}

declare module "@paypal/connect-loader-component/dist" {
  declare module.exports: any;
}

declare module "@paypal/connect-loader-component/dist/lib/safeLoadBtModule" {
  declare module.exports: any;
}

declare module "@paypal/connect-loader-component/dist/lib/safeLoadBtModule/types" {
  declare module.exports: any;
}

declare module "@paypal/connect-loader-component/dist/loadAxoScript" {
  declare module.exports: any;
}

declare module "@paypal/connect-loader-component/dist/types" {
  declare module.exports: any;
}

declare module "@paypal/connect-loader-component/load-axo-script" {
  declare module.exports: any;
}

// Filename aliases
declare module "@paypal/connect-loader-component/dist/constants.js" {
  declare module.exports: $Exports<"@paypal/connect-loader-component/dist/constants">;
}
declare module "@paypal/connect-loader-component/dist/index" {
  declare module.exports: $Exports<"@paypal/connect-loader-component/dist">;
}
declare module "@paypal/connect-loader-component/dist/index.js" {
  declare module.exports: $Exports<"@paypal/connect-loader-component/dist">;
}
declare module "@paypal/connect-loader-component/dist/lib/safeLoadBtModule/index" {
  declare module.exports: $Exports<"@paypal/connect-loader-component/dist/lib/safeLoadBtModule">;
}
declare module "@paypal/connect-loader-component/dist/lib/safeLoadBtModule/index.js" {
  declare module.exports: $Exports<"@paypal/connect-loader-component/dist/lib/safeLoadBtModule">;
}
declare module "@paypal/connect-loader-component/dist/lib/safeLoadBtModule/types.js" {
  declare module.exports: $Exports<"@paypal/connect-loader-component/dist/lib/safeLoadBtModule/types">;
}
declare module "@paypal/connect-loader-component/dist/loadAxoScript.js" {
  declare module.exports: $Exports<"@paypal/connect-loader-component/dist/loadAxoScript">;
}
declare module "@paypal/connect-loader-component/dist/types.js" {
  declare module.exports: $Exports<"@paypal/connect-loader-component/dist/types">;
}
declare module "@paypal/connect-loader-component/load-axo-script.js" {
  declare module.exports: $Exports<"@paypal/connect-loader-component/load-axo-script">;
}
