// flow-typed signature: 3229653f24ed20d08637d0f80b9fde23
// flow-typed version: <<STUB>>/@paypal/sdk-client_v^4.0.184/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/sdk-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@paypal/sdk-client" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@paypal/sdk-client/__sdk__" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/server/babel.config" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/server/constants" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/server" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/server/meta.integration.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/server/meta" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/server/meta" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/server/meta.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/server/util" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/api" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/api.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/config" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/config.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/constants" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/declarations" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/domains" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/domains.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/dpop" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/dpop.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/errors" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/events" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/experiment" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/fraudnet" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/fraudnet.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/global" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/global.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/graphql" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/graphql.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/interface" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/logger" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/meta" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/meta.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/script" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/script.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/session" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/session.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/setup" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/tracking" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/tracking.test" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/types" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/src/utils" {
  declare module.exports: any;
}

declare module "@paypal/sdk-client/test/globals" {
  declare module.exports: any;
}

// Filename aliases
declare module "@paypal/sdk-client/__sdk__.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/__sdk__">;
}
declare module "@paypal/sdk-client/index" {
  declare module.exports: $Exports<"@paypal/sdk-client">;
}
declare module "@paypal/sdk-client/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-client">;
}
declare module "@paypal/sdk-client/server/babel.config.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/server/babel.config">;
}
declare module "@paypal/sdk-client/server/constants.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/server/constants">;
}
declare module "@paypal/sdk-client/server/index" {
  declare module.exports: $Exports<"@paypal/sdk-client/server">;
}
declare module "@paypal/sdk-client/server/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/server">;
}
declare module "@paypal/sdk-client/server/meta.integration.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/server/meta.integration.test">;
}
declare module "@paypal/sdk-client/server/meta.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/server/meta">;
}
declare module "@paypal/sdk-client/server/meta.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-client/server/meta">;
}
declare module "@paypal/sdk-client/server/meta.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/server/meta.test">;
}
declare module "@paypal/sdk-client/server/util.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/server/util">;
}
declare module "@paypal/sdk-client/src/api.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/api">;
}
declare module "@paypal/sdk-client/src/api.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/api.test">;
}
declare module "@paypal/sdk-client/src/config.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/config">;
}
declare module "@paypal/sdk-client/src/config.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/config.test">;
}
declare module "@paypal/sdk-client/src/constants.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/constants">;
}
declare module "@paypal/sdk-client/src/declarations.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/declarations">;
}
declare module "@paypal/sdk-client/src/domains.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/domains">;
}
declare module "@paypal/sdk-client/src/domains.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/domains.test">;
}
declare module "@paypal/sdk-client/src/dpop.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/dpop">;
}
declare module "@paypal/sdk-client/src/dpop.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/dpop.test">;
}
declare module "@paypal/sdk-client/src/errors.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/errors">;
}
declare module "@paypal/sdk-client/src/events.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/events">;
}
declare module "@paypal/sdk-client/src/experiment.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/experiment">;
}
declare module "@paypal/sdk-client/src/fraudnet.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/fraudnet">;
}
declare module "@paypal/sdk-client/src/fraudnet.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/fraudnet.test">;
}
declare module "@paypal/sdk-client/src/global.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/global">;
}
declare module "@paypal/sdk-client/src/global.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/global.test">;
}
declare module "@paypal/sdk-client/src/graphql.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/graphql">;
}
declare module "@paypal/sdk-client/src/graphql.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/graphql.test">;
}
declare module "@paypal/sdk-client/src/index" {
  declare module.exports: $Exports<"@paypal/sdk-client/src">;
}
declare module "@paypal/sdk-client/src/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src">;
}
declare module "@paypal/sdk-client/src/interface.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/interface">;
}
declare module "@paypal/sdk-client/src/logger.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/logger">;
}
declare module "@paypal/sdk-client/src/meta.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/meta">;
}
declare module "@paypal/sdk-client/src/meta.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/meta.test">;
}
declare module "@paypal/sdk-client/src/script.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/script">;
}
declare module "@paypal/sdk-client/src/script.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/script.test">;
}
declare module "@paypal/sdk-client/src/session.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/session">;
}
declare module "@paypal/sdk-client/src/session.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/session.test">;
}
declare module "@paypal/sdk-client/src/setup.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/setup">;
}
declare module "@paypal/sdk-client/src/test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/test">;
}
declare module "@paypal/sdk-client/src/tracking.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/tracking">;
}
declare module "@paypal/sdk-client/src/tracking.test.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/tracking.test">;
}
declare module "@paypal/sdk-client/src/types.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/types">;
}
declare module "@paypal/sdk-client/src/utils.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/src/utils">;
}
declare module "@paypal/sdk-client/test/globals.js" {
  declare module.exports: $Exports<"@paypal/sdk-client/test/globals">;
}
