// flow-typed signature: 7b67a45bed7f1095aaf30d3892f52527
// flow-typed version: <<STUB>>/@paypal/sdk-constants_v^1.0.146/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/sdk-constants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@paypal/sdk-constants" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@paypal/sdk-constants/dist/module/apm" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/defaults" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/env" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/error" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/fpti" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/funding" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/locale" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/observability" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/order" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/params" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/platform" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/module/types" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/paypal-sdk-constants" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/dist/paypal-sdk-constants.min" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/apm" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/defaults" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/env" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/error" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/fpti" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/funding" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/locale" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/observability" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/order" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/params" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/platform" {
  declare module.exports: any;
}

declare module "@paypal/sdk-constants/src/types" {
  declare module.exports: any;
}

// Filename aliases
declare module "@paypal/sdk-constants/dist/module/apm.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/apm">;
}
declare module "@paypal/sdk-constants/dist/module/defaults.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/defaults">;
}
declare module "@paypal/sdk-constants/dist/module/env.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/env">;
}
declare module "@paypal/sdk-constants/dist/module/error.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/error">;
}
declare module "@paypal/sdk-constants/dist/module/fpti.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/fpti">;
}
declare module "@paypal/sdk-constants/dist/module/funding.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/funding">;
}
declare module "@paypal/sdk-constants/dist/module/index" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module">;
}
declare module "@paypal/sdk-constants/dist/module/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module">;
}
declare module "@paypal/sdk-constants/dist/module/locale.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/locale">;
}
declare module "@paypal/sdk-constants/dist/module/observability.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/observability">;
}
declare module "@paypal/sdk-constants/dist/module/order.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/order">;
}
declare module "@paypal/sdk-constants/dist/module/params.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/params">;
}
declare module "@paypal/sdk-constants/dist/module/platform.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/platform">;
}
declare module "@paypal/sdk-constants/dist/module/types.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/module/types">;
}
declare module "@paypal/sdk-constants/dist/paypal-sdk-constants.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/paypal-sdk-constants">;
}
declare module "@paypal/sdk-constants/dist/paypal-sdk-constants.min.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/dist/paypal-sdk-constants.min">;
}
declare module "@paypal/sdk-constants/index" {
  declare module.exports: $Exports<"@paypal/sdk-constants">;
}
declare module "@paypal/sdk-constants/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants">;
}
declare module "@paypal/sdk-constants/src/apm.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/apm">;
}
declare module "@paypal/sdk-constants/src/defaults.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/defaults">;
}
declare module "@paypal/sdk-constants/src/env.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/env">;
}
declare module "@paypal/sdk-constants/src/error.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/error">;
}
declare module "@paypal/sdk-constants/src/fpti.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/fpti">;
}
declare module "@paypal/sdk-constants/src/funding.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/funding">;
}
declare module "@paypal/sdk-constants/src/index" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src">;
}
declare module "@paypal/sdk-constants/src/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src">;
}
declare module "@paypal/sdk-constants/src/locale.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/locale">;
}
declare module "@paypal/sdk-constants/src/observability.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/observability">;
}
declare module "@paypal/sdk-constants/src/order.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/order">;
}
declare module "@paypal/sdk-constants/src/params.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/params">;
}
declare module "@paypal/sdk-constants/src/platform.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/platform">;
}
declare module "@paypal/sdk-constants/src/types.js" {
  declare module.exports: $Exports<"@paypal/sdk-constants/src/types">;
}
