/* @flow */

export const testContent = {
  instantlyPayWith: "Pay instantly with",
  poweredBy: "Powered by PayPal",
  chooseCardOrShipping: "Choose card or shipping",
  useDifferentAccount: "Use different account",
  deleteVaultedAccount: "Forget this account",
  deleteVaultedCard: "Forget this card",
  chooseCard: "Choose card",
  payWithDebitOrCreditCard: "Debit or Credit Card",
  payWithDifferentAccount: "Pay with a different account",
  payWithDifferentMethod: "Pay with a different funding method",
  payNow: "Pay Now",
  payWith: "Pay with",
  credit: "Credit",
  balance: "Balance",
  payPalBalance: "PayPal balance",
  moreOptions: "More options",
  "label.checkout": "Checkout",
  "label.paypal": "PayPal",
  "label.buynow": "Buy Now",
  "label.pay": "Pay with PayPal",
  "label.installment.withPeriod": "Pay up to {period}x without interest",
  "label.installment.withoutPeriod": "Interest free payments",
};
