// flow-typed signature: d73c5d9cd278e81838435aaf6bf5eb0f
// flow-typed version: <<STUB>>/Base64_v^1.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'Base64'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'Base64' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'Base64/base64' {
  declare module.exports: any;
}

// Filename aliases
declare module 'Base64/base64.js' {
  declare module.exports: $Exports<'Base64/base64'>;
}
