// flow-typed signature: ee2d82a40200502dd6a9c2f1b2cbebc8
// flow-typed version: <<STUB>>/beaver-logger_v^3.0.6/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'beaver-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'beaver-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'beaver-logger/client/builders' {
  declare module.exports: any;
}

declare module 'beaver-logger/client/config' {
  declare module.exports: any;
}

declare module 'beaver-logger/client' {
  declare module.exports: any;
}

declare module 'beaver-logger/client/init' {
  declare module.exports: any;
}

declare module 'beaver-logger/client/interface' {
  declare module.exports: any;
}

declare module 'beaver-logger/client/logger' {
  declare module.exports: any;
}

declare module 'beaver-logger/client/performance' {
  declare module.exports: any;
}

declare module 'beaver-logger/client/transitions' {
  declare module.exports: any;
}

declare module 'beaver-logger/client/util' {
  declare module.exports: any;
}

declare module 'beaver-logger/dist/beaver-logger' {
  declare module.exports: any;
}

declare module 'beaver-logger/dist/beaver-logger.min' {
  declare module.exports: any;
}

declare module 'beaver-logger/server' {
  declare module.exports: any;
}

declare module 'beaver-logger/server/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'beaver-logger/client/builders.js' {
  declare module.exports: $Exports<'beaver-logger/client/builders'>;
}
declare module 'beaver-logger/client/config.js' {
  declare module.exports: $Exports<'beaver-logger/client/config'>;
}
declare module 'beaver-logger/client/index' {
  declare module.exports: $Exports<'beaver-logger/client'>;
}
declare module 'beaver-logger/client/index.js' {
  declare module.exports: $Exports<'beaver-logger/client'>;
}
declare module 'beaver-logger/client/init.js' {
  declare module.exports: $Exports<'beaver-logger/client/init'>;
}
declare module 'beaver-logger/client/interface.js' {
  declare module.exports: $Exports<'beaver-logger/client/interface'>;
}
declare module 'beaver-logger/client/logger.js' {
  declare module.exports: $Exports<'beaver-logger/client/logger'>;
}
declare module 'beaver-logger/client/performance.js' {
  declare module.exports: $Exports<'beaver-logger/client/performance'>;
}
declare module 'beaver-logger/client/transitions.js' {
  declare module.exports: $Exports<'beaver-logger/client/transitions'>;
}
declare module 'beaver-logger/client/util.js' {
  declare module.exports: $Exports<'beaver-logger/client/util'>;
}
declare module 'beaver-logger/dist/beaver-logger.js' {
  declare module.exports: $Exports<'beaver-logger/dist/beaver-logger'>;
}
declare module 'beaver-logger/dist/beaver-logger.min.js' {
  declare module.exports: $Exports<'beaver-logger/dist/beaver-logger.min'>;
}
declare module 'beaver-logger/index' {
  declare module.exports: $Exports<'beaver-logger'>;
}
declare module 'beaver-logger/index.js' {
  declare module.exports: $Exports<'beaver-logger'>;
}
declare module 'beaver-logger/server/index' {
  declare module.exports: $Exports<'beaver-logger/server'>;
}
declare module 'beaver-logger/server/index.js' {
  declare module.exports: $Exports<'beaver-logger/server'>;
}
declare module 'beaver-logger/server/util.js' {
  declare module.exports: $Exports<'beaver-logger/server/util'>;
}
