// flow-typed signature: 74a2802124e380dfbbd8f74fcc7875ba
// flow-typed version: <<STUB>>/grabthar-release_v1.0.69/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grabthar-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grabthar-release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grabthar-release/scripts/cdnify' {
  declare module.exports: any;
}

declare module 'grabthar-release/scripts/prune' {
  declare module.exports: any;
}

declare module 'grabthar-release/scripts/validate-flat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grabthar-release/scripts/cdnify.js' {
  declare module.exports: $Exports<'grabthar-release/scripts/cdnify'>;
}
declare module 'grabthar-release/scripts/prune.js' {
  declare module.exports: $Exports<'grabthar-release/scripts/prune'>;
}
declare module 'grabthar-release/scripts/validate-flat.js' {
  declare module.exports: $Exports<'grabthar-release/scripts/validate-flat'>;
}
