// flow-typed signature: 90955b584fada597a7df8d385b633a2c
// flow-typed version: <<STUB>>/hi-base32_v^0.5.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hi-base32'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hi-base32' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hi-base32/build/base32.min' {
  declare module.exports: any;
}

declare module 'hi-base32/src/base32' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hi-base32/build/base32.min.js' {
  declare module.exports: $Exports<'hi-base32/build/base32.min'>;
}
declare module 'hi-base32/src/base32.js' {
  declare module.exports: $Exports<'hi-base32/src/base32'>;
}
