// flow-typed signature: d7ec5708f8a2f12b248917275bcd4ee6
// flow-typed version: <<STUB>>/imagemagick_v^0.1.3/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemagick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "imagemagick" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "imagemagick/imagemagick" {
  declare module.exports: any;
}

declare module "imagemagick/test-crop" {
  declare module.exports: any;
}

declare module "imagemagick/test" {
  declare module.exports: any;
}

// Filename aliases
declare module "imagemagick/imagemagick.js" {
  declare module.exports: $Exports<"imagemagick/imagemagick">;
}
declare module "imagemagick/test-crop.js" {
  declare module.exports: $Exports<"imagemagick/test-crop">;
}
declare module "imagemagick/test.js" {
  declare module.exports: $Exports<"imagemagick/test">;
}
