// flow-typed signature: 152b6ebb4fa1370b5b9bd87b95acace3
// flow-typed version: <<STUB>>/imgur_v^0.3.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imgur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "imgur" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "imgur/__tests__/getAPIUrl" {
  declare module.exports: any;
}

declare module "imgur/__tests__/getClientId" {
  declare module.exports: any;
}

declare module "imgur/__tests__/getMashapeKey" {
  declare module.exports: any;
}

declare module "imgur/__tests__/imgurRequest" {
  declare module.exports: any;
}

declare module "imgur/__tests__/search" {
  declare module.exports: any;
}

declare module "imgur/__tests__/setAPIUrl" {
  declare module.exports: any;
}

declare module "imgur/__tests__/setClientId" {
  declare module.exports: any;
}

declare module "imgur/__tests__/setMashapeKey" {
  declare module.exports: any;
}

declare module "imgur/__tests__/uploadUrl" {
  declare module.exports: any;
}

declare module "imgur/cli" {
  declare module.exports: any;
}

declare module "imgur/lib/imgur" {
  declare module.exports: any;
}

// Filename aliases
declare module "imgur/__tests__/getAPIUrl.js" {
  declare module.exports: $Exports<"imgur/__tests__/getAPIUrl">;
}
declare module "imgur/__tests__/getClientId.js" {
  declare module.exports: $Exports<"imgur/__tests__/getClientId">;
}
declare module "imgur/__tests__/getMashapeKey.js" {
  declare module.exports: $Exports<"imgur/__tests__/getMashapeKey">;
}
declare module "imgur/__tests__/imgurRequest.js" {
  declare module.exports: $Exports<"imgur/__tests__/imgurRequest">;
}
declare module "imgur/__tests__/search.js" {
  declare module.exports: $Exports<"imgur/__tests__/search">;
}
declare module "imgur/__tests__/setAPIUrl.js" {
  declare module.exports: $Exports<"imgur/__tests__/setAPIUrl">;
}
declare module "imgur/__tests__/setClientId.js" {
  declare module.exports: $Exports<"imgur/__tests__/setClientId">;
}
declare module "imgur/__tests__/setMashapeKey.js" {
  declare module.exports: $Exports<"imgur/__tests__/setMashapeKey">;
}
declare module "imgur/__tests__/uploadUrl.js" {
  declare module.exports: $Exports<"imgur/__tests__/uploadUrl">;
}
declare module "imgur/cli.js" {
  declare module.exports: $Exports<"imgur/cli">;
}
declare module "imgur/lib/imgur.js" {
  declare module.exports: $Exports<"imgur/lib/imgur">;
}
