// flow-typed signature: a618e4e596e8d45bda2c7994f6bcfa02
// flow-typed version: <<STUB>>/imgur_v^0.2.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imgur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imgur' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imgur/cli' {
  declare module.exports: any;
}

declare module 'imgur/lib/imgur' {
  declare module.exports: any;
}

declare module 'imgur/test/getAPIUrl' {
  declare module.exports: any;
}

declare module 'imgur/test/getClientId' {
  declare module.exports: any;
}

declare module 'imgur/test/getMashapeKey' {
  declare module.exports: any;
}

declare module 'imgur/test/imgurRequest' {
  declare module.exports: any;
}

declare module 'imgur/test/setAPIUrl' {
  declare module.exports: any;
}

declare module 'imgur/test/setClientId' {
  declare module.exports: any;
}

declare module 'imgur/test/setMashapeKey' {
  declare module.exports: any;
}

declare module 'imgur/test/uploadUrl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imgur/cli.js' {
  declare module.exports: $Exports<'imgur/cli'>;
}
declare module 'imgur/lib/imgur.js' {
  declare module.exports: $Exports<'imgur/lib/imgur'>;
}
declare module 'imgur/test/getAPIUrl.js' {
  declare module.exports: $Exports<'imgur/test/getAPIUrl'>;
}
declare module 'imgur/test/getClientId.js' {
  declare module.exports: $Exports<'imgur/test/getClientId'>;
}
declare module 'imgur/test/getMashapeKey.js' {
  declare module.exports: $Exports<'imgur/test/getMashapeKey'>;
}
declare module 'imgur/test/imgurRequest.js' {
  declare module.exports: $Exports<'imgur/test/imgurRequest'>;
}
declare module 'imgur/test/setAPIUrl.js' {
  declare module.exports: $Exports<'imgur/test/setAPIUrl'>;
}
declare module 'imgur/test/setClientId.js' {
  declare module.exports: $Exports<'imgur/test/setClientId'>;
}
declare module 'imgur/test/setMashapeKey.js' {
  declare module.exports: $Exports<'imgur/test/setMashapeKey'>;
}
declare module 'imgur/test/uploadUrl.js' {
  declare module.exports: $Exports<'imgur/test/uploadUrl'>;
}
