// flow-typed signature: a9d09ddd674b88969f8707ffd664f001
// flow-typed version: <<STUB>>/memory-fs_v^0.5.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memory-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "memory-fs" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "memory-fs/lib/join" {
  declare module.exports: any;
}

declare module "memory-fs/lib/MemoryFileSystem" {
  declare module.exports: any;
}

declare module "memory-fs/lib/MemoryFileSystemError" {
  declare module.exports: any;
}

declare module "memory-fs/lib/normalize" {
  declare module.exports: any;
}

// Filename aliases
declare module "memory-fs/lib/join.js" {
  declare module.exports: $Exports<"memory-fs/lib/join">;
}
declare module "memory-fs/lib/MemoryFileSystem.js" {
  declare module.exports: $Exports<"memory-fs/lib/MemoryFileSystem">;
}
declare module "memory-fs/lib/MemoryFileSystemError.js" {
  declare module.exports: $Exports<"memory-fs/lib/MemoryFileSystemError">;
}
declare module "memory-fs/lib/normalize.js" {
  declare module.exports: $Exports<"memory-fs/lib/normalize">;
}
