// flow-typed signature: 957abd883023c73e831fc962ea202774
// flow-typed version: <<STUB>>/pixelmatch_v^4.0.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixelmatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pixelmatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pixelmatch/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pixelmatch/index' {
  declare module.exports: $Exports<'pixelmatch'>;
}
declare module 'pixelmatch/index.js' {
  declare module.exports: $Exports<'pixelmatch'>;
}
declare module 'pixelmatch/test/test.js' {
  declare module.exports: $Exports<'pixelmatch/test/test'>;
}
