// flow-typed signature: 15fac8cbd8ca065beb9ad069a9c2c9a0
// flow-typed version: <<STUB>>/prettier-plugin-sh_v^0.10.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-plugin-sh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prettier-plugin-sh" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prettier-plugin-sh/lib" {
  declare module.exports: any;
}

declare module "prettier-plugin-sh/lib/languages" {
  declare module.exports: any;
}

// Filename aliases
declare module "prettier-plugin-sh/lib/index" {
  declare module.exports: $Exports<"prettier-plugin-sh/lib">;
}
declare module "prettier-plugin-sh/lib/index.js" {
  declare module.exports: $Exports<"prettier-plugin-sh/lib">;
}
declare module "prettier-plugin-sh/lib/languages.js" {
  declare module.exports: $Exports<"prettier-plugin-sh/lib/languages">;
}
