// flow-typed signature: 0160d42a343484fabafe356ba00e7450
// flow-typed version: <<STUB>>/sync-browser-mocks_v^1.0.43/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sync-browser-mocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sync-browser-mocks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sync-browser-mocks/dist/sync-browser-mocks' {
  declare module.exports: any;
}

declare module 'sync-browser-mocks/dist/sync-browser-mocks.min' {
  declare module.exports: any;
}

declare module 'sync-browser-mocks/src' {
  declare module.exports: any;
}

declare module 'sync-browser-mocks/src/postMessage' {
  declare module.exports: any;
}

declare module 'sync-browser-mocks/src/promise' {
  declare module.exports: any;
}

declare module 'sync-browser-mocks/src/timeout' {
  declare module.exports: any;
}

declare module 'sync-browser-mocks/src/xhr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sync-browser-mocks/dist/sync-browser-mocks.js' {
  declare module.exports: $Exports<'sync-browser-mocks/dist/sync-browser-mocks'>;
}
declare module 'sync-browser-mocks/dist/sync-browser-mocks.min.js' {
  declare module.exports: $Exports<'sync-browser-mocks/dist/sync-browser-mocks.min'>;
}
declare module 'sync-browser-mocks/src/index' {
  declare module.exports: $Exports<'sync-browser-mocks/src'>;
}
declare module 'sync-browser-mocks/src/index.js' {
  declare module.exports: $Exports<'sync-browser-mocks/src'>;
}
declare module 'sync-browser-mocks/src/postMessage.js' {
  declare module.exports: $Exports<'sync-browser-mocks/src/postMessage'>;
}
declare module 'sync-browser-mocks/src/promise.js' {
  declare module.exports: $Exports<'sync-browser-mocks/src/promise'>;
}
declare module 'sync-browser-mocks/src/timeout.js' {
  declare module.exports: $Exports<'sync-browser-mocks/src/timeout'>;
}
declare module 'sync-browser-mocks/src/xhr.js' {
  declare module.exports: $Exports<'sync-browser-mocks/src/xhr'>;
}
