// flow-typed signature: a3ed8c76be0da833735ca142116e02a4
// flow-typed version: <<STUB>>/vitest_v^1.3.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vitest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "vitest" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "vitest/dist/browser" {
  declare module.exports: any;
}

declare module "vitest/dist/chunks/install-pkg.LE8oaA1t" {
  declare module.exports: any;
}

declare module "vitest/dist/chunks/integrations-globals.THajbSRg" {
  declare module.exports: any;
}

declare module "vitest/dist/chunks/node-git.Hw101KjS" {
  declare module.exports: any;
}

declare module "vitest/dist/chunks/runtime-console.Iloo9fIt" {
  declare module.exports: any;
}

declare module "vitest/dist/chunks/runtime-runBaseTests.9RbsHRbU" {
  declare module.exports: any;
}

declare module "vitest/dist/cli-wrapper" {
  declare module.exports: any;
}

declare module "vitest/dist/cli" {
  declare module.exports: any;
}

declare module "vitest/dist/config" {
  declare module.exports: any;
}

declare module "vitest/dist/coverage" {
  declare module.exports: any;
}

declare module "vitest/dist/environments" {
  declare module.exports: any;
}

declare module "vitest/dist/execute" {
  declare module.exports: any;
}

declare module "vitest/dist" {
  declare module.exports: any;
}

declare module "vitest/dist/node" {
  declare module.exports: any;
}

declare module "vitest/dist/path" {
  declare module.exports: any;
}

declare module "vitest/dist/reporters" {
  declare module.exports: any;
}

declare module "vitest/dist/runners" {
  declare module.exports: any;
}

declare module "vitest/dist/spy" {
  declare module.exports: any;
}

declare module "vitest/dist/suite" {
  declare module.exports: any;
}

declare module "vitest/dist/utils" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/_commonjsHelpers.jjO7Zipk" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/base.N3JkKp7j" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/base.Z38YsPLm" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/benchmark.eeqk2rd8" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/cac.wWT9ELdg" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/constants.K-Wf1PUy" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/coverage.E7sG1b3r" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/date.Ns1pGd_X" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/execute.27Kk4lQF" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/global.CkGT_TMy" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/index.8bPxjt7g" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/index.9hqYxJUw" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/index.c1V_jzyZ" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/index.GVFv9dZ0" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/index.ir9i0ywP" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/index.JZMafwT-" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/index.xL8XjTLv" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/rpc.joBhAkyK" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/run-once.Olz_Zkd8" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/setup-common.snyQUvE3" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/tasks.IknbGB2n" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/utils.GbToHGHI" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/vi.C5mroSoP" {
  declare module.exports: any;
}

declare module "vitest/dist/vendor/vm.o1IruPAo" {
  declare module.exports: any;
}

declare module "vitest/dist/worker" {
  declare module.exports: any;
}

declare module "vitest/dist/workers" {
  declare module.exports: any;
}

declare module "vitest/dist/workers/forks" {
  declare module.exports: any;
}

declare module "vitest/dist/workers/runVmTests" {
  declare module.exports: any;
}

declare module "vitest/dist/workers/threads" {
  declare module.exports: any;
}

declare module "vitest/dist/workers/vmForks" {
  declare module.exports: any;
}

declare module "vitest/dist/workers/vmThreads" {
  declare module.exports: any;
}

// Filename aliases
declare module "vitest/dist/browser.js" {
  declare module.exports: $Exports<"vitest/dist/browser">;
}
declare module "vitest/dist/chunks/install-pkg.LE8oaA1t.js" {
  declare module.exports: $Exports<"vitest/dist/chunks/install-pkg.LE8oaA1t">;
}
declare module "vitest/dist/chunks/integrations-globals.THajbSRg.js" {
  declare module.exports: $Exports<"vitest/dist/chunks/integrations-globals.THajbSRg">;
}
declare module "vitest/dist/chunks/node-git.Hw101KjS.js" {
  declare module.exports: $Exports<"vitest/dist/chunks/node-git.Hw101KjS">;
}
declare module "vitest/dist/chunks/runtime-console.Iloo9fIt.js" {
  declare module.exports: $Exports<"vitest/dist/chunks/runtime-console.Iloo9fIt">;
}
declare module "vitest/dist/chunks/runtime-runBaseTests.9RbsHRbU.js" {
  declare module.exports: $Exports<"vitest/dist/chunks/runtime-runBaseTests.9RbsHRbU">;
}
declare module "vitest/dist/cli-wrapper.js" {
  declare module.exports: $Exports<"vitest/dist/cli-wrapper">;
}
declare module "vitest/dist/cli.js" {
  declare module.exports: $Exports<"vitest/dist/cli">;
}
declare module "vitest/dist/config.js" {
  declare module.exports: $Exports<"vitest/dist/config">;
}
declare module "vitest/dist/coverage.js" {
  declare module.exports: $Exports<"vitest/dist/coverage">;
}
declare module "vitest/dist/environments.js" {
  declare module.exports: $Exports<"vitest/dist/environments">;
}
declare module "vitest/dist/execute.js" {
  declare module.exports: $Exports<"vitest/dist/execute">;
}
declare module "vitest/dist/index" {
  declare module.exports: $Exports<"vitest/dist">;
}
declare module "vitest/dist/index.js" {
  declare module.exports: $Exports<"vitest/dist">;
}
declare module "vitest/dist/node.js" {
  declare module.exports: $Exports<"vitest/dist/node">;
}
declare module "vitest/dist/path.js" {
  declare module.exports: $Exports<"vitest/dist/path">;
}
declare module "vitest/dist/reporters.js" {
  declare module.exports: $Exports<"vitest/dist/reporters">;
}
declare module "vitest/dist/runners.js" {
  declare module.exports: $Exports<"vitest/dist/runners">;
}
declare module "vitest/dist/spy.js" {
  declare module.exports: $Exports<"vitest/dist/spy">;
}
declare module "vitest/dist/suite.js" {
  declare module.exports: $Exports<"vitest/dist/suite">;
}
declare module "vitest/dist/utils.js" {
  declare module.exports: $Exports<"vitest/dist/utils">;
}
declare module "vitest/dist/vendor/_commonjsHelpers.jjO7Zipk.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/_commonjsHelpers.jjO7Zipk">;
}
declare module "vitest/dist/vendor/base.N3JkKp7j.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/base.N3JkKp7j">;
}
declare module "vitest/dist/vendor/base.Z38YsPLm.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/base.Z38YsPLm">;
}
declare module "vitest/dist/vendor/benchmark.eeqk2rd8.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/benchmark.eeqk2rd8">;
}
declare module "vitest/dist/vendor/cac.wWT9ELdg.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/cac.wWT9ELdg">;
}
declare module "vitest/dist/vendor/constants.K-Wf1PUy.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/constants.K-Wf1PUy">;
}
declare module "vitest/dist/vendor/coverage.E7sG1b3r.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/coverage.E7sG1b3r">;
}
declare module "vitest/dist/vendor/date.Ns1pGd_X.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/date.Ns1pGd_X">;
}
declare module "vitest/dist/vendor/execute.27Kk4lQF.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/execute.27Kk4lQF">;
}
declare module "vitest/dist/vendor/global.CkGT_TMy.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/global.CkGT_TMy">;
}
declare module "vitest/dist/vendor/index.8bPxjt7g.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/index.8bPxjt7g">;
}
declare module "vitest/dist/vendor/index.9hqYxJUw.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/index.9hqYxJUw">;
}
declare module "vitest/dist/vendor/index.c1V_jzyZ.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/index.c1V_jzyZ">;
}
declare module "vitest/dist/vendor/index.GVFv9dZ0.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/index.GVFv9dZ0">;
}
declare module "vitest/dist/vendor/index.ir9i0ywP.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/index.ir9i0ywP">;
}
declare module "vitest/dist/vendor/index.JZMafwT-.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/index.JZMafwT-">;
}
declare module "vitest/dist/vendor/index.xL8XjTLv.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/index.xL8XjTLv">;
}
declare module "vitest/dist/vendor/rpc.joBhAkyK.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/rpc.joBhAkyK">;
}
declare module "vitest/dist/vendor/run-once.Olz_Zkd8.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/run-once.Olz_Zkd8">;
}
declare module "vitest/dist/vendor/setup-common.snyQUvE3.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/setup-common.snyQUvE3">;
}
declare module "vitest/dist/vendor/tasks.IknbGB2n.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/tasks.IknbGB2n">;
}
declare module "vitest/dist/vendor/utils.GbToHGHI.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/utils.GbToHGHI">;
}
declare module "vitest/dist/vendor/vi.C5mroSoP.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/vi.C5mroSoP">;
}
declare module "vitest/dist/vendor/vm.o1IruPAo.js" {
  declare module.exports: $Exports<"vitest/dist/vendor/vm.o1IruPAo">;
}
declare module "vitest/dist/worker.js" {
  declare module.exports: $Exports<"vitest/dist/worker">;
}
declare module "vitest/dist/workers.js" {
  declare module.exports: $Exports<"vitest/dist/workers">;
}
declare module "vitest/dist/workers/forks.js" {
  declare module.exports: $Exports<"vitest/dist/workers/forks">;
}
declare module "vitest/dist/workers/runVmTests.js" {
  declare module.exports: $Exports<"vitest/dist/workers/runVmTests">;
}
declare module "vitest/dist/workers/threads.js" {
  declare module.exports: $Exports<"vitest/dist/workers/threads">;
}
declare module "vitest/dist/workers/vmForks.js" {
  declare module.exports: $Exports<"vitest/dist/workers/vmForks">;
}
declare module "vitest/dist/workers/vmThreads.js" {
  declare module.exports: $Exports<"vitest/dist/workers/vmThreads">;
}
