// flow-typed signature: c3e2779aa39285b7fa0c8498f90f2d58
// flow-typed version: <<STUB>>/vite_v^3.2.4/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "vite" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "vite/bin/vite" {
  declare module.exports: any;
}

declare module "vite/dist/node/chunks/dep-07a79996" {
  declare module.exports: any;
}

declare module "vite/dist/node/chunks/dep-19c40c50" {
  declare module.exports: any;
}

declare module "vite/dist/node/chunks/dep-9deb2354" {
  declare module.exports: any;
}

declare module "vite/dist/node/chunks/dep-ae4d20cb" {
  declare module.exports: any;
}

declare module "vite/dist/node/chunks/dep-f11f7337" {
  declare module.exports: any;
}

declare module "vite/dist/node/cli" {
  declare module.exports: any;
}

declare module "vite/dist/node/constants" {
  declare module.exports: any;
}

declare module "vite/dist/node" {
  declare module.exports: any;
}

// Filename aliases
declare module "vite/bin/vite.js" {
  declare module.exports: $Exports<"vite/bin/vite">;
}
declare module "vite/dist/node/chunks/dep-07a79996.js" {
  declare module.exports: $Exports<"vite/dist/node/chunks/dep-07a79996">;
}
declare module "vite/dist/node/chunks/dep-19c40c50.js" {
  declare module.exports: $Exports<"vite/dist/node/chunks/dep-19c40c50">;
}
declare module "vite/dist/node/chunks/dep-9deb2354.js" {
  declare module.exports: $Exports<"vite/dist/node/chunks/dep-9deb2354">;
}
declare module "vite/dist/node/chunks/dep-ae4d20cb.js" {
  declare module.exports: $Exports<"vite/dist/node/chunks/dep-ae4d20cb">;
}
declare module "vite/dist/node/chunks/dep-f11f7337.js" {
  declare module.exports: $Exports<"vite/dist/node/chunks/dep-f11f7337">;
}
declare module "vite/dist/node/cli.js" {
  declare module.exports: $Exports<"vite/dist/node/cli">;
}
declare module "vite/dist/node/constants.js" {
  declare module.exports: $Exports<"vite/dist/node/constants">;
}
declare module "vite/dist/node/index" {
  declare module.exports: $Exports<"vite/dist/node">;
}
declare module "vite/dist/node/index.js" {
  declare module.exports: $Exports<"vite/dist/node">;
}
