// flow-typed signature: 2a206a5147ebbf576b4ec9ff50bd2f74
// flow-typed version: <<STUB>>/zoid_v6.0.87/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zoid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zoid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zoid/dist/module/component/base' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/child' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/child/props' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/child/validate' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/component' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/component/props' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/component/templates/component' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/component/templates/container' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/component/templates' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/component/validate' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/delegate' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/parent/drivers' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/parent' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/parent/props' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/parent/validate' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/component/window' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/constants' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/declarations' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/drivers/angular' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/drivers/angular2' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/drivers/ember' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/drivers/glimmer' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/drivers' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/drivers/react' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/drivers/script' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/drivers/vue' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/error' {
  declare module.exports: any;
}

declare module 'zoid/dist/module' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/interface' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/lib/css' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/lib/decorators' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/lib/dom' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/lib/fn' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/lib/global' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/lib' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/lib/logger' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/lib/promise' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/lib/util' {
  declare module.exports: any;
}

declare module 'zoid/dist/module/types' {
  declare module.exports: any;
}

declare module 'zoid/dist/zoid.frame' {
  declare module.exports: any;
}

declare module 'zoid/dist/zoid.frame.min' {
  declare module.exports: any;
}

declare module 'zoid/dist/zoid' {
  declare module.exports: any;
}

declare module 'zoid/dist/zoid.min' {
  declare module.exports: any;
}

declare module 'zoid/globals' {
  declare module.exports: any;
}

declare module 'zoid/src/component/base' {
  declare module.exports: any;
}

declare module 'zoid/src/component/child' {
  declare module.exports: any;
}

declare module 'zoid/src/component/child/props' {
  declare module.exports: any;
}

declare module 'zoid/src/component/child/validate' {
  declare module.exports: any;
}

declare module 'zoid/src/component/component' {
  declare module.exports: any;
}

declare module 'zoid/src/component/component/props' {
  declare module.exports: any;
}

declare module 'zoid/src/component/component/templates/component' {
  declare module.exports: any;
}

declare module 'zoid/src/component/component/templates/container' {
  declare module.exports: any;
}

declare module 'zoid/src/component/component/templates' {
  declare module.exports: any;
}

declare module 'zoid/src/component/component/validate' {
  declare module.exports: any;
}

declare module 'zoid/src/component/delegate' {
  declare module.exports: any;
}

declare module 'zoid/src/component' {
  declare module.exports: any;
}

declare module 'zoid/src/component/parent/drivers' {
  declare module.exports: any;
}

declare module 'zoid/src/component/parent' {
  declare module.exports: any;
}

declare module 'zoid/src/component/parent/props' {
  declare module.exports: any;
}

declare module 'zoid/src/component/parent/validate' {
  declare module.exports: any;
}

declare module 'zoid/src/component/window' {
  declare module.exports: any;
}

declare module 'zoid/src/constants' {
  declare module.exports: any;
}

declare module 'zoid/src/declarations' {
  declare module.exports: any;
}

declare module 'zoid/src/drivers/angular' {
  declare module.exports: any;
}

declare module 'zoid/src/drivers/angular2' {
  declare module.exports: any;
}

declare module 'zoid/src/drivers/ember' {
  declare module.exports: any;
}

declare module 'zoid/src/drivers/glimmer' {
  declare module.exports: any;
}

declare module 'zoid/src/drivers' {
  declare module.exports: any;
}

declare module 'zoid/src/drivers/react' {
  declare module.exports: any;
}

declare module 'zoid/src/drivers/script' {
  declare module.exports: any;
}

declare module 'zoid/src/drivers/vue' {
  declare module.exports: any;
}

declare module 'zoid/src/error' {
  declare module.exports: any;
}

declare module 'zoid/src' {
  declare module.exports: any;
}

declare module 'zoid/src/interface' {
  declare module.exports: any;
}

declare module 'zoid/src/lib/css' {
  declare module.exports: any;
}

declare module 'zoid/src/lib/decorators' {
  declare module.exports: any;
}

declare module 'zoid/src/lib/dom' {
  declare module.exports: any;
}

declare module 'zoid/src/lib/fn' {
  declare module.exports: any;
}

declare module 'zoid/src/lib/global' {
  declare module.exports: any;
}

declare module 'zoid/src/lib' {
  declare module.exports: any;
}

declare module 'zoid/src/lib/logger' {
  declare module.exports: any;
}

declare module 'zoid/src/lib/promise' {
  declare module.exports: any;
}

declare module 'zoid/src/lib/util' {
  declare module.exports: any;
}

declare module 'zoid/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zoid/dist/module/component/base.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/base'>;
}
declare module 'zoid/dist/module/component/child/index' {
  declare module.exports: $Exports<'zoid/dist/module/component/child'>;
}
declare module 'zoid/dist/module/component/child/index.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/child'>;
}
declare module 'zoid/dist/module/component/child/props.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/child/props'>;
}
declare module 'zoid/dist/module/component/child/validate.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/child/validate'>;
}
declare module 'zoid/dist/module/component/component/index' {
  declare module.exports: $Exports<'zoid/dist/module/component/component'>;
}
declare module 'zoid/dist/module/component/component/index.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/component'>;
}
declare module 'zoid/dist/module/component/component/props.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/component/props'>;
}
declare module 'zoid/dist/module/component/component/templates/component.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/component/templates/component'>;
}
declare module 'zoid/dist/module/component/component/templates/container.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/component/templates/container'>;
}
declare module 'zoid/dist/module/component/component/templates/index' {
  declare module.exports: $Exports<'zoid/dist/module/component/component/templates'>;
}
declare module 'zoid/dist/module/component/component/templates/index.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/component/templates'>;
}
declare module 'zoid/dist/module/component/component/validate.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/component/validate'>;
}
declare module 'zoid/dist/module/component/delegate/index' {
  declare module.exports: $Exports<'zoid/dist/module/component/delegate'>;
}
declare module 'zoid/dist/module/component/delegate/index.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/delegate'>;
}
declare module 'zoid/dist/module/component/index' {
  declare module.exports: $Exports<'zoid/dist/module/component'>;
}
declare module 'zoid/dist/module/component/index.js' {
  declare module.exports: $Exports<'zoid/dist/module/component'>;
}
declare module 'zoid/dist/module/component/parent/drivers.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/parent/drivers'>;
}
declare module 'zoid/dist/module/component/parent/index' {
  declare module.exports: $Exports<'zoid/dist/module/component/parent'>;
}
declare module 'zoid/dist/module/component/parent/index.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/parent'>;
}
declare module 'zoid/dist/module/component/parent/props.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/parent/props'>;
}
declare module 'zoid/dist/module/component/parent/validate.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/parent/validate'>;
}
declare module 'zoid/dist/module/component/window.js' {
  declare module.exports: $Exports<'zoid/dist/module/component/window'>;
}
declare module 'zoid/dist/module/constants.js' {
  declare module.exports: $Exports<'zoid/dist/module/constants'>;
}
declare module 'zoid/dist/module/declarations.js' {
  declare module.exports: $Exports<'zoid/dist/module/declarations'>;
}
declare module 'zoid/dist/module/drivers/angular.js' {
  declare module.exports: $Exports<'zoid/dist/module/drivers/angular'>;
}
declare module 'zoid/dist/module/drivers/angular2.js' {
  declare module.exports: $Exports<'zoid/dist/module/drivers/angular2'>;
}
declare module 'zoid/dist/module/drivers/ember.js' {
  declare module.exports: $Exports<'zoid/dist/module/drivers/ember'>;
}
declare module 'zoid/dist/module/drivers/glimmer.js' {
  declare module.exports: $Exports<'zoid/dist/module/drivers/glimmer'>;
}
declare module 'zoid/dist/module/drivers/index' {
  declare module.exports: $Exports<'zoid/dist/module/drivers'>;
}
declare module 'zoid/dist/module/drivers/index.js' {
  declare module.exports: $Exports<'zoid/dist/module/drivers'>;
}
declare module 'zoid/dist/module/drivers/react.js' {
  declare module.exports: $Exports<'zoid/dist/module/drivers/react'>;
}
declare module 'zoid/dist/module/drivers/script.js' {
  declare module.exports: $Exports<'zoid/dist/module/drivers/script'>;
}
declare module 'zoid/dist/module/drivers/vue.js' {
  declare module.exports: $Exports<'zoid/dist/module/drivers/vue'>;
}
declare module 'zoid/dist/module/error.js' {
  declare module.exports: $Exports<'zoid/dist/module/error'>;
}
declare module 'zoid/dist/module/index' {
  declare module.exports: $Exports<'zoid/dist/module'>;
}
declare module 'zoid/dist/module/index.js' {
  declare module.exports: $Exports<'zoid/dist/module'>;
}
declare module 'zoid/dist/module/interface.js' {
  declare module.exports: $Exports<'zoid/dist/module/interface'>;
}
declare module 'zoid/dist/module/lib/css.js' {
  declare module.exports: $Exports<'zoid/dist/module/lib/css'>;
}
declare module 'zoid/dist/module/lib/decorators.js' {
  declare module.exports: $Exports<'zoid/dist/module/lib/decorators'>;
}
declare module 'zoid/dist/module/lib/dom.js' {
  declare module.exports: $Exports<'zoid/dist/module/lib/dom'>;
}
declare module 'zoid/dist/module/lib/fn.js' {
  declare module.exports: $Exports<'zoid/dist/module/lib/fn'>;
}
declare module 'zoid/dist/module/lib/global.js' {
  declare module.exports: $Exports<'zoid/dist/module/lib/global'>;
}
declare module 'zoid/dist/module/lib/index' {
  declare module.exports: $Exports<'zoid/dist/module/lib'>;
}
declare module 'zoid/dist/module/lib/index.js' {
  declare module.exports: $Exports<'zoid/dist/module/lib'>;
}
declare module 'zoid/dist/module/lib/logger.js' {
  declare module.exports: $Exports<'zoid/dist/module/lib/logger'>;
}
declare module 'zoid/dist/module/lib/promise.js' {
  declare module.exports: $Exports<'zoid/dist/module/lib/promise'>;
}
declare module 'zoid/dist/module/lib/util.js' {
  declare module.exports: $Exports<'zoid/dist/module/lib/util'>;
}
declare module 'zoid/dist/module/types.js' {
  declare module.exports: $Exports<'zoid/dist/module/types'>;
}
declare module 'zoid/dist/zoid.frame.js' {
  declare module.exports: $Exports<'zoid/dist/zoid.frame'>;
}
declare module 'zoid/dist/zoid.frame.min.js' {
  declare module.exports: $Exports<'zoid/dist/zoid.frame.min'>;
}
declare module 'zoid/dist/zoid.js' {
  declare module.exports: $Exports<'zoid/dist/zoid'>;
}
declare module 'zoid/dist/zoid.min.js' {
  declare module.exports: $Exports<'zoid/dist/zoid.min'>;
}
declare module 'zoid/globals.js' {
  declare module.exports: $Exports<'zoid/globals'>;
}
declare module 'zoid/index' {
  declare module.exports: $Exports<'zoid'>;
}
declare module 'zoid/index.js' {
  declare module.exports: $Exports<'zoid'>;
}
declare module 'zoid/src/component/base.js' {
  declare module.exports: $Exports<'zoid/src/component/base'>;
}
declare module 'zoid/src/component/child/index' {
  declare module.exports: $Exports<'zoid/src/component/child'>;
}
declare module 'zoid/src/component/child/index.js' {
  declare module.exports: $Exports<'zoid/src/component/child'>;
}
declare module 'zoid/src/component/child/props.js' {
  declare module.exports: $Exports<'zoid/src/component/child/props'>;
}
declare module 'zoid/src/component/child/validate.js' {
  declare module.exports: $Exports<'zoid/src/component/child/validate'>;
}
declare module 'zoid/src/component/component/index' {
  declare module.exports: $Exports<'zoid/src/component/component'>;
}
declare module 'zoid/src/component/component/index.js' {
  declare module.exports: $Exports<'zoid/src/component/component'>;
}
declare module 'zoid/src/component/component/props.js' {
  declare module.exports: $Exports<'zoid/src/component/component/props'>;
}
declare module 'zoid/src/component/component/templates/component.jsx' {
  declare module.exports: $Exports<'zoid/src/component/component/templates/component'>;
}
declare module 'zoid/src/component/component/templates/container.jsx' {
  declare module.exports: $Exports<'zoid/src/component/component/templates/container'>;
}
declare module 'zoid/src/component/component/templates/index' {
  declare module.exports: $Exports<'zoid/src/component/component/templates'>;
}
declare module 'zoid/src/component/component/templates/index.js' {
  declare module.exports: $Exports<'zoid/src/component/component/templates'>;
}
declare module 'zoid/src/component/component/validate.js' {
  declare module.exports: $Exports<'zoid/src/component/component/validate'>;
}
declare module 'zoid/src/component/delegate/index' {
  declare module.exports: $Exports<'zoid/src/component/delegate'>;
}
declare module 'zoid/src/component/delegate/index.js' {
  declare module.exports: $Exports<'zoid/src/component/delegate'>;
}
declare module 'zoid/src/component/index' {
  declare module.exports: $Exports<'zoid/src/component'>;
}
declare module 'zoid/src/component/index.js' {
  declare module.exports: $Exports<'zoid/src/component'>;
}
declare module 'zoid/src/component/parent/drivers.js' {
  declare module.exports: $Exports<'zoid/src/component/parent/drivers'>;
}
declare module 'zoid/src/component/parent/index' {
  declare module.exports: $Exports<'zoid/src/component/parent'>;
}
declare module 'zoid/src/component/parent/index.js' {
  declare module.exports: $Exports<'zoid/src/component/parent'>;
}
declare module 'zoid/src/component/parent/props.js' {
  declare module.exports: $Exports<'zoid/src/component/parent/props'>;
}
declare module 'zoid/src/component/parent/validate.js' {
  declare module.exports: $Exports<'zoid/src/component/parent/validate'>;
}
declare module 'zoid/src/component/window.js' {
  declare module.exports: $Exports<'zoid/src/component/window'>;
}
declare module 'zoid/src/constants.js' {
  declare module.exports: $Exports<'zoid/src/constants'>;
}
declare module 'zoid/src/declarations.js' {
  declare module.exports: $Exports<'zoid/src/declarations'>;
}
declare module 'zoid/src/drivers/angular.js' {
  declare module.exports: $Exports<'zoid/src/drivers/angular'>;
}
declare module 'zoid/src/drivers/angular2.js' {
  declare module.exports: $Exports<'zoid/src/drivers/angular2'>;
}
declare module 'zoid/src/drivers/ember.js' {
  declare module.exports: $Exports<'zoid/src/drivers/ember'>;
}
declare module 'zoid/src/drivers/glimmer.js' {
  declare module.exports: $Exports<'zoid/src/drivers/glimmer'>;
}
declare module 'zoid/src/drivers/index' {
  declare module.exports: $Exports<'zoid/src/drivers'>;
}
declare module 'zoid/src/drivers/index.js' {
  declare module.exports: $Exports<'zoid/src/drivers'>;
}
declare module 'zoid/src/drivers/react.js' {
  declare module.exports: $Exports<'zoid/src/drivers/react'>;
}
declare module 'zoid/src/drivers/script.js' {
  declare module.exports: $Exports<'zoid/src/drivers/script'>;
}
declare module 'zoid/src/drivers/vue.js' {
  declare module.exports: $Exports<'zoid/src/drivers/vue'>;
}
declare module 'zoid/src/error.js' {
  declare module.exports: $Exports<'zoid/src/error'>;
}
declare module 'zoid/src/index' {
  declare module.exports: $Exports<'zoid/src'>;
}
declare module 'zoid/src/index.js' {
  declare module.exports: $Exports<'zoid/src'>;
}
declare module 'zoid/src/interface.js' {
  declare module.exports: $Exports<'zoid/src/interface'>;
}
declare module 'zoid/src/lib/css.js' {
  declare module.exports: $Exports<'zoid/src/lib/css'>;
}
declare module 'zoid/src/lib/decorators.js' {
  declare module.exports: $Exports<'zoid/src/lib/decorators'>;
}
declare module 'zoid/src/lib/dom.js' {
  declare module.exports: $Exports<'zoid/src/lib/dom'>;
}
declare module 'zoid/src/lib/fn.js' {
  declare module.exports: $Exports<'zoid/src/lib/fn'>;
}
declare module 'zoid/src/lib/global.js' {
  declare module.exports: $Exports<'zoid/src/lib/global'>;
}
declare module 'zoid/src/lib/index' {
  declare module.exports: $Exports<'zoid/src/lib'>;
}
declare module 'zoid/src/lib/index.js' {
  declare module.exports: $Exports<'zoid/src/lib'>;
}
declare module 'zoid/src/lib/logger.js' {
  declare module.exports: $Exports<'zoid/src/lib/logger'>;
}
declare module 'zoid/src/lib/promise.js' {
  declare module.exports: $Exports<'zoid/src/lib/promise'>;
}
declare module 'zoid/src/lib/util.js' {
  declare module.exports: $Exports<'zoid/src/lib/util'>;
}
declare module 'zoid/src/types.js' {
  declare module.exports: $Exports<'zoid/src/types'>;
}
