/* @flow */
/** @jsx node */

import { node, type ElementNode } from 'jsx-pragmatic/src';

import { CLASS } from '../../constants';

export function Spinner() : ?ElementNode {
    return (
        <div class={ CLASS.SPINNER }>

            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vestibulum iaculis pulvinar. Nam et massa sit amet augue iaculis tempor. Fusce a dapibus magna. Aliquam vitae purus id libero tempor eleifend. Mauris sit amet nisi leo. Proin faucibus enim ut iaculis ornare. Cras mi diam, feugiat et magna in, cursus sagittis nibh. Proin venenatis elit non lectus vehicula viverra. Sed tempus lacus et augue suscipit luctus. Praesent eleifend nisi nibh, sit amet maximus risus ornare sed. Sed volutpat pellentesque faucibus. Sed gravida vitae sapien eget ullamcorper. Proin id dolor metus.

            Cras quis risus aliquam, lacinia mi quis, iaculis odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel feugiat sapien. Duis consectetur, lacus vitae egestas commodo, arcu urna bibendum metus, eget ultrices sem nisl sit amet magna. Maecenas a tortor sed sapien ornare facilisis. Mauris mi augue, porttitor in posuere eu, tincidunt at sem. In et consectetur turpis. Sed interdum lectus dolor. Donec pharetra felis non nisl sodales, eu faucibus lorem luctus. Phasellus nec varius turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi eu molestie dui. Nullam in ligula sed turpis pharetra faucibus.

            Vivamus id pulvinar odio. Sed neque orci, interdum condimentum sapien at, aliquam sagittis arcu. Sed iaculis velit vel laoreet euismod. Nullam vel est pharetra, laoreet mi in, ullamcorper velit. Maecenas augue nibh, varius non molestie vitae, dapibus ultricies quam. Nam eu nibh aliquet, porta turpis sit amet, dapibus metus. Suspendisse a neque vitae nisi suscipit gravida. Fusce tincidunt porttitor tellus euismod mattis. Nunc condimentum dui vitae nisi lobortis, ut commodo quam fringilla.

            Praesent lobortis nisl sem, et euismod ante venenatis eget. Aliquam diam libero, consectetur non nulla ac, placerat accumsan tortor. In aliquam condimentum fringilla. Maecenas feugiat, enim eu laoreet tempor, velit sapien hendrerit metus, sed molestie orci nunc a lectus. Pellentesque eu velit ut odio auctor porta id a elit. Aliquam vel augue at sapien commodo pulvinar. Cras tempor efficitur felis sit amet lobortis. Sed porta finibus eros, id porta mauris interdum et. Phasellus finibus eros in luctus tempor. Curabitur purus metus, malesuada id tincidunt sit amet, efficitur quis odio. Nunc interdum est urna, in interdum tellus imperdiet et. Donec hendrerit, risus nec ultricies efficitur, ante velit egestas nibh, a fermentum enim ipsum sed turpis. In hac habitasse platea dictumst. Aenean sed posuere turpis, ac faucibus lectus.

            Vestibulum quis dignissim eros. Quisque at scelerisque augue. Duis in augue pulvinar, aliquam turpis eu, rhoncus augue. Maecenas consectetur sapien ac lorem aliquam, eget dignissim lacus tempus. Curabitur at luctus odio. Duis urna massa, tincidunt quis sem sit amet, eleifend mollis nunc. Morbi commodo, mi id semper pulvinar, felis eros mollis mauris, non congue magna tellus sit amet odio. Etiam suscipit nisi a ligula mattis, id consequat felis tristique. Praesent vel lacus porta, vulputate quam at, dictum velit. Phasellus dapibus ligula vel semper dignissim.

            Integer eu tempus ipsum, sed finibus felis. Cras volutpat bibendum ipsum, eu accumsan eros convallis id. Vivamus in tristique mauris. Maecenas vitae tincidunt risus. Curabitur id hendrerit leo. Aliquam tempor nunc non orci suscipit interdum. Morbi ornare, orci nec egestas accumsan, eros felis fringilla magna, non semper diam turpis at mauris. Aenean ante nibh, accumsan et convallis non, vehicula vel quam. Nulla consectetur, enim non vestibulum aliquam, urna justo tristique risus, quis condimentum dui enim et risus. Sed et consequat lorem. Maecenas gravida nunc nec elit blandit, sed ullamcorper felis sollicitudin. Ut leo velit, ultrices id justo varius, pretium scelerisque nibh. Sed tristique diam lorem, in iaculis magna sagittis a.

            Maecenas fringilla lobortis elit a posuere. Phasellus eu pellentesque nulla, ut pretium tellus. Pellentesque et magna dui. Pellentesque rhoncus ultricies mauris nec condimentum. Proin fermentum aliquam justo, sed rutrum nisl. Nullam sed porta lorem. Aenean sollicitudin, massa ut posuere bibendum, lorem nulla scelerisque orci, eu tempus eros eros sed turpis. Quisque et nisl egestas, ornare ante nec, tristique mauris. Nulla maximus lorem quis turpis sodales scelerisque. Nam condimentum, lorem et rhoncus dapibus, sem massa viverra arcu, a tincidunt risus dui eget nunc. Mauris hendrerit turpis id risus lobortis ullamcorper. Sed id ligula eget ligula tincidunt sodales. Fusce non pretium dolor. Etiam pellentesque justo nibh, vel faucibus turpis efficitur ac.

            Ut mattis ipsum elementum, efficitur sem quis, tincidunt mi. Donec ultricies gravida enim, a blandit mi accumsan ac. Suspendisse vulputate enim ligula, elementum volutpat massa blandit in. Proin eu nisi ut lorem aliquet eleifend. Morbi sed mattis tortor. Nulla fermentum leo magna, ac faucibus velit eleifend vel. Nullam scelerisque consectetur pharetra. Sed vitae enim posuere, blandit lectus ultricies, euismod massa. Nam sagittis nibh non odio porttitor, vitae faucibus lacus pellentesque. Curabitur eget enim sit amet velit hendrerit tempus.

            Curabitur eu commodo libero. Etiam justo est, ornare et dui vitae, egestas dapibus ex. Morbi vel egestas diam. Morbi facilisis, turpis et efficitur finibus, velit felis efficitur augue, ultricies faucibus erat velit et purus. Vestibulum sapien eros, ornare sed lobortis id, semper ac enim. Nunc elementum lacus quis est dapibus, eu maximus enim rutrum. Aliquam at tempus lorem, eget laoreet nibh. Duis tempus sed risus non convallis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce sapien tellus, facilisis quis convallis in, scelerisque consequat turpis.

            Suspendisse lacus est, porta vitae elit non, hendrerit rutrum sapien. In hac habitasse platea dictumst. Aenean elit odio, interdum ac facilisis vel, volutpat in magna. Sed eget convallis justo. Integer posuere pulvinar velit, nec cursus enim rhoncus vitae. Suspendisse quis lacus rutrum, efficitur nisl sed, sagittis metus. Aenean finibus dictum condimentum. Etiam ornare, eros sagittis volutpat tristique, arcu tellus ornare eros, in posuere enim libero non erat. Maecenas semper ipsum id risus rhoncus, eu finibus nunc porta. Proin vel erat sit amet metus ullamcorper malesuada in vel lorem. Maecenas vitae ligula viverra, interdum eros nec, vehicula felis. In consectetur ac erat nec convallis. Sed placerat egestas ullamcorper. Pellentesque imperdiet nulla malesuada leo ornare, id consequat nunc pharetra. Sed dictum iaculis pulvinar. Donec egestas, risus sit amet porta elementum, arcu velit efficitur ipsum, eu molestie mauris nulla quis dolor.
        </div>
    );
}
