// flow-typed signature: 2ccdd59539e51bab0bb496f8095ff8e8
// flow-typed version: <<STUB>>/@krakenjs/beaver-logger_v^5.7.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/beaver-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@krakenjs/beaver-logger" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@krakenjs/beaver-logger/dist/beaver-logger" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/beaver-logger.min" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/config" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/constants" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/declarations" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/http" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/index.test" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/logger" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/logger.test" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/types" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/util" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/dist/module/util.test" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/server/constants" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/server" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/server/server" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/config" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/constants" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/declarations" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/http" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/index.test" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/logger" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/logger.test" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/types" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/util" {
  declare module.exports: any;
}

declare module "@krakenjs/beaver-logger/src/util.test" {
  declare module.exports: any;
}

// Filename aliases
declare module "@krakenjs/beaver-logger/dist/beaver-logger.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/beaver-logger">;
}
declare module "@krakenjs/beaver-logger/dist/beaver-logger.min.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/beaver-logger.min">;
}
declare module "@krakenjs/beaver-logger/dist/module/config.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/config">;
}
declare module "@krakenjs/beaver-logger/dist/module/constants.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/constants">;
}
declare module "@krakenjs/beaver-logger/dist/module/declarations.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/declarations">;
}
declare module "@krakenjs/beaver-logger/dist/module/http.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/http">;
}
declare module "@krakenjs/beaver-logger/dist/module/index" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module">;
}
declare module "@krakenjs/beaver-logger/dist/module/index.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module">;
}
declare module "@krakenjs/beaver-logger/dist/module/index.test.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/index.test">;
}
declare module "@krakenjs/beaver-logger/dist/module/logger.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/logger">;
}
declare module "@krakenjs/beaver-logger/dist/module/logger.test.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/logger.test">;
}
declare module "@krakenjs/beaver-logger/dist/module/types.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/types">;
}
declare module "@krakenjs/beaver-logger/dist/module/util.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/util">;
}
declare module "@krakenjs/beaver-logger/dist/module/util.test.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/dist/module/util.test">;
}
declare module "@krakenjs/beaver-logger/server/constants.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/server/constants">;
}
declare module "@krakenjs/beaver-logger/server/index" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/server">;
}
declare module "@krakenjs/beaver-logger/server/index.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/server">;
}
declare module "@krakenjs/beaver-logger/server/server.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/server/server">;
}
declare module "@krakenjs/beaver-logger/src/config.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/config">;
}
declare module "@krakenjs/beaver-logger/src/constants.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/constants">;
}
declare module "@krakenjs/beaver-logger/src/declarations.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/declarations">;
}
declare module "@krakenjs/beaver-logger/src/http.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/http">;
}
declare module "@krakenjs/beaver-logger/src/index" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src">;
}
declare module "@krakenjs/beaver-logger/src/index.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src">;
}
declare module "@krakenjs/beaver-logger/src/index.test.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/index.test">;
}
declare module "@krakenjs/beaver-logger/src/logger.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/logger">;
}
declare module "@krakenjs/beaver-logger/src/logger.test.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/logger.test">;
}
declare module "@krakenjs/beaver-logger/src/types.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/types">;
}
declare module "@krakenjs/beaver-logger/src/util.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/util">;
}
declare module "@krakenjs/beaver-logger/src/util.test.js" {
  declare module.exports: $Exports<"@krakenjs/beaver-logger/src/util.test">;
}
