// flow-typed signature: b0f28bba814507c218e5d7dc56203b94
// flow-typed version: <<STUB>>/@krakenjs/sync-browser-mocks_v^3.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/sync-browser-mocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@krakenjs/sync-browser-mocks" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@krakenjs/sync-browser-mocks/dist/sync-browser-mocks" {
  declare module.exports: any;
}

declare module "@krakenjs/sync-browser-mocks/dist/sync-browser-mocks.min" {
  declare module.exports: any;
}

declare module "@krakenjs/sync-browser-mocks/src" {
  declare module.exports: any;
}

declare module "@krakenjs/sync-browser-mocks/src/timeout" {
  declare module.exports: any;
}

declare module "@krakenjs/sync-browser-mocks/src/webSocket" {
  declare module.exports: any;
}

declare module "@krakenjs/sync-browser-mocks/src/xhr" {
  declare module.exports: any;
}

// Filename aliases
declare module "@krakenjs/sync-browser-mocks/dist/sync-browser-mocks.js" {
  declare module.exports: $Exports<"@krakenjs/sync-browser-mocks/dist/sync-browser-mocks">;
}
declare module "@krakenjs/sync-browser-mocks/dist/sync-browser-mocks.min.js" {
  declare module.exports: $Exports<"@krakenjs/sync-browser-mocks/dist/sync-browser-mocks.min">;
}
declare module "@krakenjs/sync-browser-mocks/src/index" {
  declare module.exports: $Exports<"@krakenjs/sync-browser-mocks/src">;
}
declare module "@krakenjs/sync-browser-mocks/src/index.js" {
  declare module.exports: $Exports<"@krakenjs/sync-browser-mocks/src">;
}
declare module "@krakenjs/sync-browser-mocks/src/timeout.js" {
  declare module.exports: $Exports<"@krakenjs/sync-browser-mocks/src/timeout">;
}
declare module "@krakenjs/sync-browser-mocks/src/webSocket.js" {
  declare module.exports: $Exports<"@krakenjs/sync-browser-mocks/src/webSocket">;
}
declare module "@krakenjs/sync-browser-mocks/src/xhr.js" {
  declare module.exports: $Exports<"@krakenjs/sync-browser-mocks/src/xhr">;
}
