// flow-typed signature: 18561bbedb37e2b4ced64e3270ff55ae
// flow-typed version: <<STUB>>/@krakenjs/zoid_v^10.3.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/zoid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@krakenjs/zoid" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@krakenjs/zoid/dist/zoid.frame" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/dist/zoid.frame.min" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/dist/zoid.frameworks.frame" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/dist/zoid.frameworks.frame.min" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/dist/zoid.frameworks" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/dist/zoid.frameworks.min" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/dist/zoid" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/dist/zoid.min" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/globals" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/babel.config" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/child/child" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/child" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/child/props" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/component/component" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/component" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/component/props" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/component/templates/component" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/component/templates/container" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/component/templates" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/component/validate" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/constants" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/declarations" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/drivers/angular" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/drivers/angular2" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/drivers" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/drivers/react" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/drivers/vue" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/drivers/vue3" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/lib/global" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/lib" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/lib/serialize" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/lib/window" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/parent" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/parent/parent" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/parent/props" {
  declare module.exports: any;
}

declare module "@krakenjs/zoid/src/types" {
  declare module.exports: any;
}

// Filename aliases
declare module "@krakenjs/zoid/dist/zoid.frame.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/dist/zoid.frame">;
}
declare module "@krakenjs/zoid/dist/zoid.frame.min.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/dist/zoid.frame.min">;
}
declare module "@krakenjs/zoid/dist/zoid.frameworks.frame.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/dist/zoid.frameworks.frame">;
}
declare module "@krakenjs/zoid/dist/zoid.frameworks.frame.min.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/dist/zoid.frameworks.frame.min">;
}
declare module "@krakenjs/zoid/dist/zoid.frameworks.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/dist/zoid.frameworks">;
}
declare module "@krakenjs/zoid/dist/zoid.frameworks.min.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/dist/zoid.frameworks.min">;
}
declare module "@krakenjs/zoid/dist/zoid.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/dist/zoid">;
}
declare module "@krakenjs/zoid/dist/zoid.min.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/dist/zoid.min">;
}
declare module "@krakenjs/zoid/globals.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/globals">;
}
declare module "@krakenjs/zoid/index" {
  declare module.exports: $Exports<"@krakenjs/zoid">;
}
declare module "@krakenjs/zoid/index.js" {
  declare module.exports: $Exports<"@krakenjs/zoid">;
}
declare module "@krakenjs/zoid/src/babel.config.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/babel.config">;
}
declare module "@krakenjs/zoid/src/child/child.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/child/child">;
}
declare module "@krakenjs/zoid/src/child/index" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/child">;
}
declare module "@krakenjs/zoid/src/child/index.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/child">;
}
declare module "@krakenjs/zoid/src/child/props.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/child/props">;
}
declare module "@krakenjs/zoid/src/component/component.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/component/component">;
}
declare module "@krakenjs/zoid/src/component/index" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/component">;
}
declare module "@krakenjs/zoid/src/component/index.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/component">;
}
declare module "@krakenjs/zoid/src/component/props.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/component/props">;
}
declare module "@krakenjs/zoid/src/component/templates/component.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/component/templates/component">;
}
declare module "@krakenjs/zoid/src/component/templates/container.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/component/templates/container">;
}
declare module "@krakenjs/zoid/src/component/templates/index" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/component/templates">;
}
declare module "@krakenjs/zoid/src/component/templates/index.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/component/templates">;
}
declare module "@krakenjs/zoid/src/component/validate.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/component/validate">;
}
declare module "@krakenjs/zoid/src/constants.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/constants">;
}
declare module "@krakenjs/zoid/src/declarations.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/declarations">;
}
declare module "@krakenjs/zoid/src/drivers/angular.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/drivers/angular">;
}
declare module "@krakenjs/zoid/src/drivers/angular2.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/drivers/angular2">;
}
declare module "@krakenjs/zoid/src/drivers/index" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/drivers">;
}
declare module "@krakenjs/zoid/src/drivers/index.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/drivers">;
}
declare module "@krakenjs/zoid/src/drivers/react.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/drivers/react">;
}
declare module "@krakenjs/zoid/src/drivers/vue.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/drivers/vue">;
}
declare module "@krakenjs/zoid/src/drivers/vue3.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/drivers/vue3">;
}
declare module "@krakenjs/zoid/src/index" {
  declare module.exports: $Exports<"@krakenjs/zoid/src">;
}
declare module "@krakenjs/zoid/src/index.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src">;
}
declare module "@krakenjs/zoid/src/lib/global.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/lib/global">;
}
declare module "@krakenjs/zoid/src/lib/index" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/lib">;
}
declare module "@krakenjs/zoid/src/lib/index.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/lib">;
}
declare module "@krakenjs/zoid/src/lib/serialize.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/lib/serialize">;
}
declare module "@krakenjs/zoid/src/lib/window.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/lib/window">;
}
declare module "@krakenjs/zoid/src/parent/index" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/parent">;
}
declare module "@krakenjs/zoid/src/parent/index.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/parent">;
}
declare module "@krakenjs/zoid/src/parent/parent.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/parent/parent">;
}
declare module "@krakenjs/zoid/src/parent/props.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/parent/props">;
}
declare module "@krakenjs/zoid/src/types.js" {
  declare module.exports: $Exports<"@krakenjs/zoid/src/types">;
}
