// flow-typed signature: c424c17e12986a6ce7667649fd6e5d23
// flow-typed version: <<STUB>>/@paypal/funding-components_v^1.0.31/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/funding-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@paypal/funding-components" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@paypal/funding-components/__sdk__" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/server/babel.config" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/server/config" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/server/constants" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/server/cookie" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/server" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/server/remember" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/server/types" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/server/util" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/src/config" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/src/constants" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/src/eligibility" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/src" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/src/interface" {
  declare module.exports: any;
}

declare module "@paypal/funding-components/src/types" {
  declare module.exports: any;
}

// Filename aliases
declare module "@paypal/funding-components/__sdk__.js" {
  declare module.exports: $Exports<"@paypal/funding-components/__sdk__">;
}
declare module "@paypal/funding-components/index" {
  declare module.exports: $Exports<"@paypal/funding-components">;
}
declare module "@paypal/funding-components/index.js" {
  declare module.exports: $Exports<"@paypal/funding-components">;
}
declare module "@paypal/funding-components/server/babel.config.js" {
  declare module.exports: $Exports<"@paypal/funding-components/server/babel.config">;
}
declare module "@paypal/funding-components/server/config.js" {
  declare module.exports: $Exports<"@paypal/funding-components/server/config">;
}
declare module "@paypal/funding-components/server/constants.js" {
  declare module.exports: $Exports<"@paypal/funding-components/server/constants">;
}
declare module "@paypal/funding-components/server/cookie.js" {
  declare module.exports: $Exports<"@paypal/funding-components/server/cookie">;
}
declare module "@paypal/funding-components/server/index" {
  declare module.exports: $Exports<"@paypal/funding-components/server">;
}
declare module "@paypal/funding-components/server/index.js" {
  declare module.exports: $Exports<"@paypal/funding-components/server">;
}
declare module "@paypal/funding-components/server/remember.js" {
  declare module.exports: $Exports<"@paypal/funding-components/server/remember">;
}
declare module "@paypal/funding-components/server/types.js" {
  declare module.exports: $Exports<"@paypal/funding-components/server/types">;
}
declare module "@paypal/funding-components/server/util.js" {
  declare module.exports: $Exports<"@paypal/funding-components/server/util">;
}
declare module "@paypal/funding-components/src/config.js" {
  declare module.exports: $Exports<"@paypal/funding-components/src/config">;
}
declare module "@paypal/funding-components/src/constants.js" {
  declare module.exports: $Exports<"@paypal/funding-components/src/constants">;
}
declare module "@paypal/funding-components/src/eligibility.js" {
  declare module.exports: $Exports<"@paypal/funding-components/src/eligibility">;
}
declare module "@paypal/funding-components/src/index" {
  declare module.exports: $Exports<"@paypal/funding-components/src">;
}
declare module "@paypal/funding-components/src/index.js" {
  declare module.exports: $Exports<"@paypal/funding-components/src">;
}
declare module "@paypal/funding-components/src/interface.js" {
  declare module.exports: $Exports<"@paypal/funding-components/src/interface">;
}
declare module "@paypal/funding-components/src/types.js" {
  declare module.exports: $Exports<"@paypal/funding-components/src/types">;
}
