// flow-typed signature: 47c74357060d722f2d45c2fb446747c5
// flow-typed version: <<STUB>>/@paypal/sdk-logos_v^2.2.6/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/sdk-logos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@paypal/sdk-logos" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@paypal/sdk-logos/dist/module/constants" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/lib/components" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/lib" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/lib/util" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/applepay" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/applepay/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/applepay/mark" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/bancontact" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/bancontact/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/bank/glyph" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/bank/glyph/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/bank" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/blik" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/blik/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/boleto" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/boleto/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/amex" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/amex/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/discover" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/discover/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/elo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/elo/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/glyph" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/glyph/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/hiper" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/hiper/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/jcb" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/jcb/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/mastercard" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/mastercard/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/visa" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/card/visa/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/credit" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/credit/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/credit/mark" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/eps" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/eps/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/giropay" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/giropay/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/ideal" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/ideal/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/itau" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/itau/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/mercadopago" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/mercadopago/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/multibanco" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/multibanco/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/mybank" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/mybank/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/oxxo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/oxxo/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/p24" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/p24/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/paidy" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/paidy/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/paypal" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/paypal/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/paypal/mark" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/payu" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/payu/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/satispay" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/satispay/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/sepa" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/sepa/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/sofort" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/sofort/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/trustly" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/trustly/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/venmo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/venmo/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/wechatpay" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/logos/wechatpay/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/module/types" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/paypal-sdk-logos" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/dist/paypal-sdk-logos.min" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/constants" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/lib/components" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/lib" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/lib/util" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/applepay" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/applepay/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/applepay/mark" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/bancontact" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/bancontact/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/bank/glyph" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/bank/glyph/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/bank" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/blik" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/blik/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/boleto" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/boleto/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/amex" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/amex/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/discover" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/discover/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/elo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/elo/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/glyph" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/glyph/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/hiper" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/hiper/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/jcb" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/jcb/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/mastercard" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/mastercard/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/visa" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/card/visa/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/credit" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/credit/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/credit/mark" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/eps" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/eps/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/giropay" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/giropay/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/ideal" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/ideal/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/itau" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/itau/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/mercadopago" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/mercadopago/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/multibanco" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/multibanco/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/mybank" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/mybank/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/oxxo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/oxxo/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/p24" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/p24/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/paidy" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/paidy/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/paypal" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/paypal/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/paypal/mark" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/payu" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/payu/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/satispay" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/satispay/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/sepa" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/sepa/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/sofort" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/sofort/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/trustly" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/trustly/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/venmo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/venmo/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/wechatpay" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/logos/wechatpay/logo" {
  declare module.exports: any;
}

declare module "@paypal/sdk-logos/src/types" {
  declare module.exports: any;
}

// Filename aliases
declare module "@paypal/sdk-logos/dist/module/constants.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/constants">;
}
declare module "@paypal/sdk-logos/dist/module/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module">;
}
declare module "@paypal/sdk-logos/dist/module/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module">;
}
declare module "@paypal/sdk-logos/dist/module/lib/components.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/lib/components">;
}
declare module "@paypal/sdk-logos/dist/module/lib/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/lib">;
}
declare module "@paypal/sdk-logos/dist/module/lib/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/lib">;
}
declare module "@paypal/sdk-logos/dist/module/lib/util.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/lib/util">;
}
declare module "@paypal/sdk-logos/dist/module/logos/applepay/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/applepay">;
}
declare module "@paypal/sdk-logos/dist/module/logos/applepay/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/applepay">;
}
declare module "@paypal/sdk-logos/dist/module/logos/applepay/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/applepay/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/applepay/mark.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/applepay/mark">;
}
declare module "@paypal/sdk-logos/dist/module/logos/bancontact/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/bancontact">;
}
declare module "@paypal/sdk-logos/dist/module/logos/bancontact/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/bancontact">;
}
declare module "@paypal/sdk-logos/dist/module/logos/bancontact/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/bancontact/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/bank/glyph/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/bank/glyph">;
}
declare module "@paypal/sdk-logos/dist/module/logos/bank/glyph/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/bank/glyph">;
}
declare module "@paypal/sdk-logos/dist/module/logos/bank/glyph/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/bank/glyph/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/bank/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/bank">;
}
declare module "@paypal/sdk-logos/dist/module/logos/bank/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/bank">;
}
declare module "@paypal/sdk-logos/dist/module/logos/blik/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/blik">;
}
declare module "@paypal/sdk-logos/dist/module/logos/blik/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/blik">;
}
declare module "@paypal/sdk-logos/dist/module/logos/blik/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/blik/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/boleto/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/boleto">;
}
declare module "@paypal/sdk-logos/dist/module/logos/boleto/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/boleto">;
}
declare module "@paypal/sdk-logos/dist/module/logos/boleto/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/boleto/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/amex/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/amex">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/amex/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/amex">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/amex/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/amex/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/discover/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/discover">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/discover/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/discover">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/discover/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/discover/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/elo/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/elo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/elo/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/elo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/elo/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/elo/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/glyph/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/glyph">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/glyph/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/glyph">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/glyph/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/glyph/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/hiper/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/hiper">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/hiper/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/hiper">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/hiper/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/hiper/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/jcb/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/jcb">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/jcb/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/jcb">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/jcb/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/jcb/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/mastercard/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/mastercard">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/mastercard/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/mastercard">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/mastercard/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/mastercard/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/visa/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/visa">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/visa/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/visa">;
}
declare module "@paypal/sdk-logos/dist/module/logos/card/visa/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/card/visa/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/credit/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/credit">;
}
declare module "@paypal/sdk-logos/dist/module/logos/credit/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/credit">;
}
declare module "@paypal/sdk-logos/dist/module/logos/credit/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/credit/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/credit/mark.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/credit/mark">;
}
declare module "@paypal/sdk-logos/dist/module/logos/eps/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/eps">;
}
declare module "@paypal/sdk-logos/dist/module/logos/eps/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/eps">;
}
declare module "@paypal/sdk-logos/dist/module/logos/eps/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/eps/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/giropay/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/giropay">;
}
declare module "@paypal/sdk-logos/dist/module/logos/giropay/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/giropay">;
}
declare module "@paypal/sdk-logos/dist/module/logos/giropay/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/giropay/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/ideal/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/ideal">;
}
declare module "@paypal/sdk-logos/dist/module/logos/ideal/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/ideal">;
}
declare module "@paypal/sdk-logos/dist/module/logos/ideal/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/ideal/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos">;
}
declare module "@paypal/sdk-logos/dist/module/logos/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos">;
}
declare module "@paypal/sdk-logos/dist/module/logos/itau/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/itau">;
}
declare module "@paypal/sdk-logos/dist/module/logos/itau/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/itau">;
}
declare module "@paypal/sdk-logos/dist/module/logos/itau/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/itau/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/mercadopago/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/mercadopago">;
}
declare module "@paypal/sdk-logos/dist/module/logos/mercadopago/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/mercadopago">;
}
declare module "@paypal/sdk-logos/dist/module/logos/mercadopago/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/mercadopago/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/multibanco/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/multibanco">;
}
declare module "@paypal/sdk-logos/dist/module/logos/multibanco/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/multibanco">;
}
declare module "@paypal/sdk-logos/dist/module/logos/multibanco/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/multibanco/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/mybank/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/mybank">;
}
declare module "@paypal/sdk-logos/dist/module/logos/mybank/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/mybank">;
}
declare module "@paypal/sdk-logos/dist/module/logos/mybank/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/mybank/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/oxxo/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/oxxo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/oxxo/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/oxxo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/oxxo/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/oxxo/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/p24/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/p24">;
}
declare module "@paypal/sdk-logos/dist/module/logos/p24/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/p24">;
}
declare module "@paypal/sdk-logos/dist/module/logos/p24/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/p24/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/paidy/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/paidy">;
}
declare module "@paypal/sdk-logos/dist/module/logos/paidy/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/paidy">;
}
declare module "@paypal/sdk-logos/dist/module/logos/paidy/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/paidy/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/paypal/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/paypal">;
}
declare module "@paypal/sdk-logos/dist/module/logos/paypal/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/paypal">;
}
declare module "@paypal/sdk-logos/dist/module/logos/paypal/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/paypal/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/paypal/mark.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/paypal/mark">;
}
declare module "@paypal/sdk-logos/dist/module/logos/payu/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/payu">;
}
declare module "@paypal/sdk-logos/dist/module/logos/payu/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/payu">;
}
declare module "@paypal/sdk-logos/dist/module/logos/payu/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/payu/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/satispay/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/satispay">;
}
declare module "@paypal/sdk-logos/dist/module/logos/satispay/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/satispay">;
}
declare module "@paypal/sdk-logos/dist/module/logos/satispay/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/satispay/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/sepa/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/sepa">;
}
declare module "@paypal/sdk-logos/dist/module/logos/sepa/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/sepa">;
}
declare module "@paypal/sdk-logos/dist/module/logos/sepa/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/sepa/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/sofort/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/sofort">;
}
declare module "@paypal/sdk-logos/dist/module/logos/sofort/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/sofort">;
}
declare module "@paypal/sdk-logos/dist/module/logos/sofort/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/sofort/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/trustly/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/trustly">;
}
declare module "@paypal/sdk-logos/dist/module/logos/trustly/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/trustly">;
}
declare module "@paypal/sdk-logos/dist/module/logos/trustly/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/trustly/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/venmo/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/venmo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/venmo/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/venmo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/venmo/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/venmo/logo">;
}
declare module "@paypal/sdk-logos/dist/module/logos/wechatpay/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/wechatpay">;
}
declare module "@paypal/sdk-logos/dist/module/logos/wechatpay/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/wechatpay">;
}
declare module "@paypal/sdk-logos/dist/module/logos/wechatpay/logo.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/logos/wechatpay/logo">;
}
declare module "@paypal/sdk-logos/dist/module/types.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/module/types">;
}
declare module "@paypal/sdk-logos/dist/paypal-sdk-logos.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/paypal-sdk-logos">;
}
declare module "@paypal/sdk-logos/dist/paypal-sdk-logos.min.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/dist/paypal-sdk-logos.min">;
}
declare module "@paypal/sdk-logos/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos">;
}
declare module "@paypal/sdk-logos/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos">;
}
declare module "@paypal/sdk-logos/src/constants.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/constants">;
}
declare module "@paypal/sdk-logos/src/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src">;
}
declare module "@paypal/sdk-logos/src/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src">;
}
declare module "@paypal/sdk-logos/src/lib/components.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/lib/components">;
}
declare module "@paypal/sdk-logos/src/lib/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/lib">;
}
declare module "@paypal/sdk-logos/src/lib/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/lib">;
}
declare module "@paypal/sdk-logos/src/lib/util.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/lib/util">;
}
declare module "@paypal/sdk-logos/src/logos/applepay/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/applepay">;
}
declare module "@paypal/sdk-logos/src/logos/applepay/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/applepay">;
}
declare module "@paypal/sdk-logos/src/logos/applepay/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/applepay/logo">;
}
declare module "@paypal/sdk-logos/src/logos/applepay/mark.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/applepay/mark">;
}
declare module "@paypal/sdk-logos/src/logos/bancontact/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/bancontact">;
}
declare module "@paypal/sdk-logos/src/logos/bancontact/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/bancontact">;
}
declare module "@paypal/sdk-logos/src/logos/bancontact/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/bancontact/logo">;
}
declare module "@paypal/sdk-logos/src/logos/bank/glyph/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/bank/glyph">;
}
declare module "@paypal/sdk-logos/src/logos/bank/glyph/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/bank/glyph">;
}
declare module "@paypal/sdk-logos/src/logos/bank/glyph/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/bank/glyph/logo">;
}
declare module "@paypal/sdk-logos/src/logos/bank/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/bank">;
}
declare module "@paypal/sdk-logos/src/logos/bank/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/bank">;
}
declare module "@paypal/sdk-logos/src/logos/blik/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/blik">;
}
declare module "@paypal/sdk-logos/src/logos/blik/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/blik">;
}
declare module "@paypal/sdk-logos/src/logos/blik/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/blik/logo">;
}
declare module "@paypal/sdk-logos/src/logos/boleto/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/boleto">;
}
declare module "@paypal/sdk-logos/src/logos/boleto/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/boleto">;
}
declare module "@paypal/sdk-logos/src/logos/boleto/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/boleto/logo">;
}
declare module "@paypal/sdk-logos/src/logos/card/amex/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/amex">;
}
declare module "@paypal/sdk-logos/src/logos/card/amex/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/amex">;
}
declare module "@paypal/sdk-logos/src/logos/card/amex/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/amex/logo">;
}
declare module "@paypal/sdk-logos/src/logos/card/discover/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/discover">;
}
declare module "@paypal/sdk-logos/src/logos/card/discover/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/discover">;
}
declare module "@paypal/sdk-logos/src/logos/card/discover/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/discover/logo">;
}
declare module "@paypal/sdk-logos/src/logos/card/elo/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/elo">;
}
declare module "@paypal/sdk-logos/src/logos/card/elo/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/elo">;
}
declare module "@paypal/sdk-logos/src/logos/card/elo/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/elo/logo">;
}
declare module "@paypal/sdk-logos/src/logos/card/glyph/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/glyph">;
}
declare module "@paypal/sdk-logos/src/logos/card/glyph/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/glyph">;
}
declare module "@paypal/sdk-logos/src/logos/card/glyph/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/glyph/logo">;
}
declare module "@paypal/sdk-logos/src/logos/card/hiper/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/hiper">;
}
declare module "@paypal/sdk-logos/src/logos/card/hiper/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/hiper">;
}
declare module "@paypal/sdk-logos/src/logos/card/hiper/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/hiper/logo">;
}
declare module "@paypal/sdk-logos/src/logos/card/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card">;
}
declare module "@paypal/sdk-logos/src/logos/card/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card">;
}
declare module "@paypal/sdk-logos/src/logos/card/jcb/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/jcb">;
}
declare module "@paypal/sdk-logos/src/logos/card/jcb/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/jcb">;
}
declare module "@paypal/sdk-logos/src/logos/card/jcb/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/jcb/logo">;
}
declare module "@paypal/sdk-logos/src/logos/card/mastercard/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/mastercard">;
}
declare module "@paypal/sdk-logos/src/logos/card/mastercard/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/mastercard">;
}
declare module "@paypal/sdk-logos/src/logos/card/mastercard/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/mastercard/logo">;
}
declare module "@paypal/sdk-logos/src/logos/card/visa/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/visa">;
}
declare module "@paypal/sdk-logos/src/logos/card/visa/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/visa">;
}
declare module "@paypal/sdk-logos/src/logos/card/visa/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/card/visa/logo">;
}
declare module "@paypal/sdk-logos/src/logos/credit/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/credit">;
}
declare module "@paypal/sdk-logos/src/logos/credit/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/credit">;
}
declare module "@paypal/sdk-logos/src/logos/credit/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/credit/logo">;
}
declare module "@paypal/sdk-logos/src/logos/credit/mark.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/credit/mark">;
}
declare module "@paypal/sdk-logos/src/logos/eps/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/eps">;
}
declare module "@paypal/sdk-logos/src/logos/eps/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/eps">;
}
declare module "@paypal/sdk-logos/src/logos/eps/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/eps/logo">;
}
declare module "@paypal/sdk-logos/src/logos/giropay/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/giropay">;
}
declare module "@paypal/sdk-logos/src/logos/giropay/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/giropay">;
}
declare module "@paypal/sdk-logos/src/logos/giropay/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/giropay/logo">;
}
declare module "@paypal/sdk-logos/src/logos/ideal/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/ideal">;
}
declare module "@paypal/sdk-logos/src/logos/ideal/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/ideal">;
}
declare module "@paypal/sdk-logos/src/logos/ideal/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/ideal/logo">;
}
declare module "@paypal/sdk-logos/src/logos/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos">;
}
declare module "@paypal/sdk-logos/src/logos/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos">;
}
declare module "@paypal/sdk-logos/src/logos/itau/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/itau">;
}
declare module "@paypal/sdk-logos/src/logos/itau/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/itau">;
}
declare module "@paypal/sdk-logos/src/logos/itau/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/itau/logo">;
}
declare module "@paypal/sdk-logos/src/logos/mercadopago/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/mercadopago">;
}
declare module "@paypal/sdk-logos/src/logos/mercadopago/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/mercadopago">;
}
declare module "@paypal/sdk-logos/src/logos/mercadopago/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/mercadopago/logo">;
}
declare module "@paypal/sdk-logos/src/logos/multibanco/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/multibanco">;
}
declare module "@paypal/sdk-logos/src/logos/multibanco/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/multibanco">;
}
declare module "@paypal/sdk-logos/src/logos/multibanco/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/multibanco/logo">;
}
declare module "@paypal/sdk-logos/src/logos/mybank/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/mybank">;
}
declare module "@paypal/sdk-logos/src/logos/mybank/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/mybank">;
}
declare module "@paypal/sdk-logos/src/logos/mybank/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/mybank/logo">;
}
declare module "@paypal/sdk-logos/src/logos/oxxo/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/oxxo">;
}
declare module "@paypal/sdk-logos/src/logos/oxxo/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/oxxo">;
}
declare module "@paypal/sdk-logos/src/logos/oxxo/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/oxxo/logo">;
}
declare module "@paypal/sdk-logos/src/logos/p24/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/p24">;
}
declare module "@paypal/sdk-logos/src/logos/p24/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/p24">;
}
declare module "@paypal/sdk-logos/src/logos/p24/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/p24/logo">;
}
declare module "@paypal/sdk-logos/src/logos/paidy/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/paidy">;
}
declare module "@paypal/sdk-logos/src/logos/paidy/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/paidy">;
}
declare module "@paypal/sdk-logos/src/logos/paidy/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/paidy/logo">;
}
declare module "@paypal/sdk-logos/src/logos/paypal/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/paypal">;
}
declare module "@paypal/sdk-logos/src/logos/paypal/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/paypal">;
}
declare module "@paypal/sdk-logos/src/logos/paypal/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/paypal/logo">;
}
declare module "@paypal/sdk-logos/src/logos/paypal/mark.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/paypal/mark">;
}
declare module "@paypal/sdk-logos/src/logos/payu/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/payu">;
}
declare module "@paypal/sdk-logos/src/logos/payu/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/payu">;
}
declare module "@paypal/sdk-logos/src/logos/payu/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/payu/logo">;
}
declare module "@paypal/sdk-logos/src/logos/satispay/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/satispay">;
}
declare module "@paypal/sdk-logos/src/logos/satispay/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/satispay">;
}
declare module "@paypal/sdk-logos/src/logos/satispay/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/satispay/logo">;
}
declare module "@paypal/sdk-logos/src/logos/sepa/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/sepa">;
}
declare module "@paypal/sdk-logos/src/logos/sepa/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/sepa">;
}
declare module "@paypal/sdk-logos/src/logos/sepa/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/sepa/logo">;
}
declare module "@paypal/sdk-logos/src/logos/sofort/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/sofort">;
}
declare module "@paypal/sdk-logos/src/logos/sofort/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/sofort">;
}
declare module "@paypal/sdk-logos/src/logos/sofort/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/sofort/logo">;
}
declare module "@paypal/sdk-logos/src/logos/trustly/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/trustly">;
}
declare module "@paypal/sdk-logos/src/logos/trustly/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/trustly">;
}
declare module "@paypal/sdk-logos/src/logos/trustly/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/trustly/logo">;
}
declare module "@paypal/sdk-logos/src/logos/venmo/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/venmo">;
}
declare module "@paypal/sdk-logos/src/logos/venmo/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/venmo">;
}
declare module "@paypal/sdk-logos/src/logos/venmo/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/venmo/logo">;
}
declare module "@paypal/sdk-logos/src/logos/wechatpay/index" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/wechatpay">;
}
declare module "@paypal/sdk-logos/src/logos/wechatpay/index.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/wechatpay">;
}
declare module "@paypal/sdk-logos/src/logos/wechatpay/logo.jsx" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/logos/wechatpay/logo">;
}
declare module "@paypal/sdk-logos/src/types.js" {
  declare module.exports: $Exports<"@paypal/sdk-logos/src/types">;
}
