// flow-typed signature: aff1fc16242982820da2eb0e7672becc
// flow-typed version: <<STUB>>/@percy/playwright_v^1.0.4/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@percy/playwright'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@percy/playwright" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "@percy/playwright/index" {
  declare module.exports: $Exports<"@percy/playwright">;
}
declare module "@percy/playwright/index.js" {
  declare module.exports: $Exports<"@percy/playwright">;
}
