// flow-typed signature: 27783d700455718c9d0aae24925509c6
// flow-typed version: <<STUB>>/@percy/cli_v1.28.5/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@percy/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@percy/cli" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@percy/cli/dist/commands" {
  declare module.exports: any;
}

declare module "@percy/cli/dist" {
  declare module.exports: any;
}

declare module "@percy/cli/dist/percy" {
  declare module.exports: any;
}

declare module "@percy/cli/dist/update" {
  declare module.exports: any;
}

// Filename aliases
declare module "@percy/cli/dist/commands.js" {
  declare module.exports: $Exports<"@percy/cli/dist/commands">;
}
declare module "@percy/cli/dist/index" {
  declare module.exports: $Exports<"@percy/cli/dist">;
}
declare module "@percy/cli/dist/index.js" {
  declare module.exports: $Exports<"@percy/cli/dist">;
}
declare module "@percy/cli/dist/percy.js" {
  declare module.exports: $Exports<"@percy/cli/dist/percy">;
}
declare module "@percy/cli/dist/update.js" {
  declare module.exports: $Exports<"@percy/cli/dist/update">;
}
