
export let config = {

    scriptUrl: `//www.paypalobjects.com/api/${__FILE_NAME__}`,

    ppobjects: false,

    env: 'production',

    state: 'ppxo_xcomponent',

    locale: {
        country: 'US',
        lang: 'en'
    },

    enableBridge: true,

    paypalUrls: {
        local: 'http://localhost.paypal.com:8000',
        sandbox: 'https://www.sandbox.paypal.com',
        production: 'https://www.paypal.com'
    },

    get checkoutUrls() {
        return {
            local:      `${config.paypalUrls.local}/webapps/hermes`,
            sandbox:    `${config.paypalUrls.sandbox}/checkoutnow`,
            production: `${config.paypalUrls.production}/checkoutnow`
        };
    },

    get billingUrls() {
        return {
            local:      `${config.paypalUrls.local}/webapps/hermes/agreements`,
            sandbox:    `${config.paypalUrls.sandbox}/agreements/approve`,
            production: `${config.paypalUrls.production}/agreements/approve`
        };
    },

    get paypalUrl() {
        if (!config.paypalUrls[config.env]) {
            throw new Error(`Invalid env: ${config.env}`);
        }

        return config.paypalUrls[config.env];
    },

    get bridgeUrl() {
        return `${config.paypalUrl}/webapps/hermes/component-meta`;
    },

    get loggerUrl() {
        return `${config.paypalUrl}/webapps/hermes/api/logger`;
    },

    locales: {
        AD: ['zh', 'es', 'fr', 'en'],
        AE: ['ar', 'zh', 'es', 'fr', 'en'],
        AG: ['zh', 'es', 'fr', 'en'],
        AI: ['zh', 'es', 'fr', 'en'],
        AL: ['en'],
        AM: ['zh', 'es', 'fr', 'en'],
        AN: ['zh', 'es', 'fr', 'en'],
        AO: ['zh', 'es', 'fr', 'en'],
        AR: ['en', 'es'],
        AT: ['de', 'en'],
        AU: ['en'],
        AW: ['zh', 'es', 'fr', 'en'],
        AZ: ['zh', 'es', 'fr', 'en'],
        BA: ['en'],
        BB: ['zh', 'es', 'fr', 'en'],
        BE: ['nl', 'fr', 'en'],
        BF: ['zh', 'es', 'en', 'fr'],
        BG: ['en'],
        BH: ['zh', 'es', 'fr', 'en', 'ar'],
        BI: ['zh', 'es', 'en', 'fr'],
        BJ: ['zh', 'es', 'en', 'fr'],
        BM: ['zh', 'es', 'fr', 'en'],
        BN: ['en'],
        BO: ['zh', 'fr', 'en', 'es'],
        BR: ['pt', 'en'],
        BS: ['zh', 'es', 'fr', 'en'],
        BT: ['en'],
        BW: ['zh', 'es', 'fr', 'en'],
        BY: ['en'],
        BZ: ['zh', 'fr', 'en', 'es'],
        C2: ['zh', 'en'],
        CA: ['fr', 'en'],
        CD: ['zh', 'es', 'en', 'fr'],
        CG: ['zh', 'es', 'fr', 'en'],
        CH: ['fr', 'en', 'de'],
        CI: ['en', 'fr'],
        CK: ['zh', 'es', 'fr', 'en'],
        CL: ['zh', 'fr', 'en', 'es'],
        CM: ['en', 'fr'],
        CN: ['zh'],
        CO: ['zh', 'fr', 'en', 'es'],
        CR: ['zh', 'fr', 'en', 'es'],
        CV: ['zh', 'es', 'fr', 'en'],
        CY: ['en'],
        CZ: ['zh', 'fr', 'es', 'en'],
        DE: ['en', 'de'],
        DJ: ['zh', 'es', 'en', 'fr'],
        DK: ['en', 'da'],
        DM: ['zh', 'es', 'fr', 'en'],
        DO: ['zh', 'fr', 'en', 'es'],
        DZ: ['zh', 'es', 'fr', 'en', 'ar'],
        EC: ['zh', 'fr', 'en', 'es'],
        EE: ['zh', 'ru', 'fr', 'es', 'en'],
        EG: ['zh', 'es', 'fr', 'en', 'ar'],
        ER: ['zh', 'es', 'fr', 'en'],
        ES: ['es', 'en'],
        ET: ['zh', 'es', 'fr', 'en'],
        FI: ['zh', 'fr', 'es', 'en'],
        FJ: ['zh', 'es', 'fr', 'en'],
        FK: ['zh', 'es', 'fr', 'en'],
        FM: ['en'],
        FO: ['zh', 'es', 'fr', 'en', 'da'],
        FR: ['fr', 'en'],
        GA: ['zh', 'es', 'en', 'fr'],
        GB: ['fr', 'en'],
        GD: ['zh', 'es', 'fr', 'en'],
        GE: ['zh', 'es', 'fr', 'en'],
        GF: ['zh', 'es', 'fr', 'en'],
        GI: ['zh', 'es', 'fr', 'en'],
        GL: ['zh', 'es', 'fr', 'en', 'da'],
        GM: ['zh', 'es', 'fr', 'en'],
        GN: ['zh', 'es', 'en', 'fr'],
        GP: ['zh', 'es', 'fr', 'en'],
        GR: ['zh', 'fr', 'es', 'en'],
        GT: ['zh', 'fr', 'en', 'es'],
        GW: ['zh', 'es', 'fr', 'en'],
        GY: ['zh', 'es', 'fr', 'en'],
        HK: ['zh', 'en'],
        HN: ['zh', 'fr', 'en', 'es'],
        HR: ['en'],
        HU: ['zh', 'fr', 'es', 'en'],
        ID: ['id', 'en'],
        IE: ['zh', 'fr', 'es', 'en'],
        IL: ['he', 'en'],
        IN: ['en'],
        IS: ['en'],
        IT: ['it', 'en'],
        JM: ['zh', 'fr', 'en', 'es'],
        JO: ['zh', 'es', 'fr', 'en', 'ar'],
        JP: ['ja', 'en'],
        KE: ['zh', 'es', 'fr', 'en'],
        KG: ['zh', 'es', 'fr', 'en'],
        KH: ['en'],
        KI: ['zh', 'es', 'fr', 'en'],
        KM: ['zh', 'es', 'en', 'fr'],
        KN: ['zh', 'es', 'fr', 'en'],
        KR: ['ko', 'en'],
        KW: ['zh', 'es', 'fr', 'en', 'ar'],
        KY: ['zh', 'es', 'fr', 'en'],
        KZ: ['zh', 'es', 'fr', 'en'],
        LA: ['en'],
        LC: ['zh', 'es', 'fr', 'en'],
        LI: ['zh', 'es', 'fr', 'en'],
        LK: ['en'],
        LS: ['zh', 'es', 'fr', 'en'],
        LT: ['zh', 'ru', 'fr', 'es', 'en'],
        LU: ['zh', 'fr', 'es', 'en', 'de'],
        LV: ['zh', 'ru', 'fr', 'es', 'en'],
        MA: ['zh', 'es', 'fr', 'en', 'ar'],
        MC: ['en', 'fr'],
        MD: ['en'],
        ME: ['en'],
        MG: ['zh', 'es', 'fr', 'en'],
        MH: ['zh', 'es', 'fr', 'en'],
        MK: ['en'],
        ML: ['zh', 'es', 'en', 'fr'],
        MN: ['en'],
        MQ: ['zh', 'es', 'fr', 'en'],
        MR: ['zh', 'es', 'fr', 'en'],
        MS: ['zh', 'es', 'fr', 'en'],
        MT: ['en'],
        MU: ['zh', 'es', 'fr', 'en'],
        MV: ['en'],
        MW: ['zh', 'es', 'fr', 'en'],
        MX: ['es', 'en'],
        MY: ['en'],
        MZ: ['zh', 'es', 'fr', 'en'],
        NA: ['zh', 'es', 'fr', 'en'],
        NC: ['zh', 'es', 'fr', 'en'],
        NE: ['zh', 'es', 'en', 'fr'],
        NF: ['zh', 'es', 'fr', 'en'],
        NG: ['en'],
        NI: ['zh', 'fr', 'en', 'es'],
        NL: ['nl', 'en'],
        NO: ['no', 'en'],
        NP: ['en'],
        NR: ['zh', 'es', 'fr', 'en'],
        NU: ['zh', 'es', 'fr', 'en'],
        NZ: ['zh', 'fr', 'es', 'en'],
        OM: ['zh', 'es', 'fr', 'en', 'ar'],
        PA: ['zh', 'fr', 'en', 'es'],
        PE: ['zh', 'fr', 'en', 'es'],
        PF: ['zh', 'es', 'fr', 'en'],
        PG: ['zh', 'es', 'fr', 'en'],
        PH: ['en'],
        PL: ['pl', 'en'],
        PM: ['zh', 'es', 'fr', 'en'],
        PN: ['zh', 'es', 'fr', 'en'],
        PT: ['pt', 'en'],
        PW: ['zh', 'es', 'fr', 'en'],
        PY: ['en', 'es'],
        QA: ['ar', 'zh', 'es', 'fr', 'en'],
        RE: ['zh', 'es', 'fr', 'en'],
        RO: ['zh', 'fr', 'es', 'en'],
        RS: ['zh', 'es', 'fr', 'en'],
        RU: ['ru', 'en'],
        RW: ['zh', 'es', 'en', 'fr'],
        SA: ['zh', 'es', 'fr', 'en', 'ar'],
        SB: ['zh', 'es', 'fr', 'en'],
        SC: ['zh', 'es', 'en', 'fr'],
        SE: ['sv', 'en'],
        SG: ['en'],
        SH: ['zh', 'es', 'fr', 'en'],
        SI: ['zh', 'fr', 'es', 'en'],
        SJ: ['zh', 'es', 'fr', 'en'],
        SK: ['zh', 'fr', 'es', 'en'],
        SL: ['zh', 'es', 'fr', 'en'],
        SM: ['zh', 'es', 'fr', 'en'],
        SN: ['zh', 'es', 'en', 'fr'],
        SO: ['zh', 'es', 'fr', 'en'],
        SR: ['zh', 'es', 'fr', 'en'],
        ST: ['zh', 'es', 'fr', 'en'],
        SV: ['zh', 'fr', 'en', 'es'],
        SZ: ['zh', 'es', 'fr', 'en'],
        TC: ['zh', 'es', 'fr', 'en'],
        TD: ['zh', 'es', 'en', 'fr'],
        TG: ['zh', 'es', 'en', 'fr'],
        TH: ['th', 'en'],
        TJ: ['zh', 'es', 'fr', 'en'],
        TM: ['zh', 'es', 'fr', 'en'],
        TN: ['zh', 'es', 'fr', 'en', 'ar'],
        TO: ['en'],
        TR: ['tr', 'en'],
        TT: ['zh', 'es', 'fr', 'en'],
        TV: ['zh', 'es', 'fr', 'en'],
        TW: ['zh', 'en'],
        TZ: ['zh', 'es', 'fr', 'en'],
        UA: ['zh', 'ru', 'fr', 'es', 'en'],
        UG: ['zh', 'es', 'fr', 'en'],
        US: ['zh', 'fr', 'es', 'en'],
        UY: ['zh', 'fr', 'en', 'es'],
        VA: ['zh', 'es', 'fr', 'en'],
        VC: ['zh', 'es', 'fr', 'en'],
        VE: ['zh', 'fr', 'en', 'es'],
        VG: ['zh', 'es', 'fr', 'en'],
        VN: ['en'],
        VU: ['zh', 'es', 'fr', 'en'],
        WF: ['zh', 'es', 'fr', 'en'],
        WS: ['en'],
        YE: ['zh', 'es', 'fr', 'en', 'ar'],
        YT: ['zh', 'es', 'fr', 'en'],
        ZA: ['zh', 'es', 'fr', 'en'],
        ZM: ['zh', 'es', 'fr', 'en'],
        ZW: ['en']
    }
};

// Best-guess for current env

let currentDomain = `${window.location.protocol}//${window.location.host}`;

for (let env of Object.keys(config.paypalUrls)) {
    if (config.paypalUrls[env] === currentDomain) {
        config.env = env;
        break;
    }
}
