#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check if not running in GitHub Actions
if [ -z "$CI" ]; then
    echo "Running pre-push hook in local environment"
    npm run buttondiff
    exit 0
else
    echo "Skipping pre-push hook in CI environment"
    exit 0
fi
