// flow-typed signature: 2e915ecc39dd9aa5baa236ea6c93dd31
// flow-typed version: <<STUB>>/conventional-changelog-cli_v^2.0.34/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conventional-changelog-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "conventional-changelog-cli" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "conventional-changelog-cli/cli" {
  declare module.exports: any;
}

// Filename aliases
declare module "conventional-changelog-cli/cli.js" {
  declare module.exports: $Exports<"conventional-changelog-cli/cli">;
}
