// flow-typed signature: 0566a477e675fcfc2bb3a2d769dd0a0f
// flow-typed version: <<STUB>>/mocketeer_v^0.3.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocketeer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "mocketeer" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "mocketeer/dist/es/handlers/handle" {
  declare module.exports: any;
}

declare module "mocketeer/dist/es/handlers/headers" {
  declare module.exports: any;
}

declare module "mocketeer/dist/es/handlers" {
  declare module.exports: any;
}

declare module "mocketeer/dist/es/handlers/methods" {
  declare module.exports: any;
}

declare module "mocketeer/dist/es/handlers/static" {
  declare module.exports: any;
}

declare module "mocketeer/dist/es/handlers/webpack" {
  declare module.exports: any;
}

declare module "mocketeer/dist/es" {
  declare module.exports: any;
}

declare module "mocketeer/dist/es/mock" {
  declare module.exports: any;
}

// Filename aliases
declare module "mocketeer/dist/es/handlers/handle.js" {
  declare module.exports: $Exports<"mocketeer/dist/es/handlers/handle">;
}
declare module "mocketeer/dist/es/handlers/headers.js" {
  declare module.exports: $Exports<"mocketeer/dist/es/handlers/headers">;
}
declare module "mocketeer/dist/es/handlers/index" {
  declare module.exports: $Exports<"mocketeer/dist/es/handlers">;
}
declare module "mocketeer/dist/es/handlers/index.js" {
  declare module.exports: $Exports<"mocketeer/dist/es/handlers">;
}
declare module "mocketeer/dist/es/handlers/methods.js" {
  declare module.exports: $Exports<"mocketeer/dist/es/handlers/methods">;
}
declare module "mocketeer/dist/es/handlers/static.js" {
  declare module.exports: $Exports<"mocketeer/dist/es/handlers/static">;
}
declare module "mocketeer/dist/es/handlers/webpack.js" {
  declare module.exports: $Exports<"mocketeer/dist/es/handlers/webpack">;
}
declare module "mocketeer/dist/es/index" {
  declare module.exports: $Exports<"mocketeer/dist/es">;
}
declare module "mocketeer/dist/es/index.js" {
  declare module.exports: $Exports<"mocketeer/dist/es">;
}
declare module "mocketeer/dist/es/mock.js" {
  declare module.exports: $Exports<"mocketeer/dist/es/mock">;
}
