// flow-typed signature: 136e3a6b8bd3b99b53dcec248ff2f28f
// flow-typed version: <<STUB>>/pixelmatch_v^5.2.1/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixelmatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "pixelmatch" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "pixelmatch/index" {
  declare module.exports: $Exports<"pixelmatch">;
}
declare module "pixelmatch/index.js" {
  declare module.exports: $Exports<"pixelmatch">;
}
