// flow-typed signature: f67e73e7949ffd435feee30ed477d352
// flow-typed version: <<STUB>>/pngjs_v^6.0.0/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pngjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "pngjs" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "pngjs/browser" {
  declare module.exports: any;
}

declare module "pngjs/lib/bitmapper" {
  declare module.exports: any;
}

declare module "pngjs/lib/bitpacker" {
  declare module.exports: any;
}

declare module "pngjs/lib/chunkstream" {
  declare module.exports: any;
}

declare module "pngjs/lib/constants" {
  declare module.exports: any;
}

declare module "pngjs/lib/crc" {
  declare module.exports: any;
}

declare module "pngjs/lib/filter-pack" {
  declare module.exports: any;
}

declare module "pngjs/lib/filter-parse-async" {
  declare module.exports: any;
}

declare module "pngjs/lib/filter-parse-sync" {
  declare module.exports: any;
}

declare module "pngjs/lib/filter-parse" {
  declare module.exports: any;
}

declare module "pngjs/lib/format-normaliser" {
  declare module.exports: any;
}

declare module "pngjs/lib/interlace" {
  declare module.exports: any;
}

declare module "pngjs/lib/packer-async" {
  declare module.exports: any;
}

declare module "pngjs/lib/packer-sync" {
  declare module.exports: any;
}

declare module "pngjs/lib/packer" {
  declare module.exports: any;
}

declare module "pngjs/lib/paeth-predictor" {
  declare module.exports: any;
}

declare module "pngjs/lib/parser-async" {
  declare module.exports: any;
}

declare module "pngjs/lib/parser-sync" {
  declare module.exports: any;
}

declare module "pngjs/lib/parser" {
  declare module.exports: any;
}

declare module "pngjs/lib/png-sync" {
  declare module.exports: any;
}

declare module "pngjs/lib/png" {
  declare module.exports: any;
}

declare module "pngjs/lib/sync-inflate" {
  declare module.exports: any;
}

declare module "pngjs/lib/sync-reader" {
  declare module.exports: any;
}

// Filename aliases
declare module "pngjs/browser.js" {
  declare module.exports: $Exports<"pngjs/browser">;
}
declare module "pngjs/lib/bitmapper.js" {
  declare module.exports: $Exports<"pngjs/lib/bitmapper">;
}
declare module "pngjs/lib/bitpacker.js" {
  declare module.exports: $Exports<"pngjs/lib/bitpacker">;
}
declare module "pngjs/lib/chunkstream.js" {
  declare module.exports: $Exports<"pngjs/lib/chunkstream">;
}
declare module "pngjs/lib/constants.js" {
  declare module.exports: $Exports<"pngjs/lib/constants">;
}
declare module "pngjs/lib/crc.js" {
  declare module.exports: $Exports<"pngjs/lib/crc">;
}
declare module "pngjs/lib/filter-pack.js" {
  declare module.exports: $Exports<"pngjs/lib/filter-pack">;
}
declare module "pngjs/lib/filter-parse-async.js" {
  declare module.exports: $Exports<"pngjs/lib/filter-parse-async">;
}
declare module "pngjs/lib/filter-parse-sync.js" {
  declare module.exports: $Exports<"pngjs/lib/filter-parse-sync">;
}
declare module "pngjs/lib/filter-parse.js" {
  declare module.exports: $Exports<"pngjs/lib/filter-parse">;
}
declare module "pngjs/lib/format-normaliser.js" {
  declare module.exports: $Exports<"pngjs/lib/format-normaliser">;
}
declare module "pngjs/lib/interlace.js" {
  declare module.exports: $Exports<"pngjs/lib/interlace">;
}
declare module "pngjs/lib/packer-async.js" {
  declare module.exports: $Exports<"pngjs/lib/packer-async">;
}
declare module "pngjs/lib/packer-sync.js" {
  declare module.exports: $Exports<"pngjs/lib/packer-sync">;
}
declare module "pngjs/lib/packer.js" {
  declare module.exports: $Exports<"pngjs/lib/packer">;
}
declare module "pngjs/lib/paeth-predictor.js" {
  declare module.exports: $Exports<"pngjs/lib/paeth-predictor">;
}
declare module "pngjs/lib/parser-async.js" {
  declare module.exports: $Exports<"pngjs/lib/parser-async">;
}
declare module "pngjs/lib/parser-sync.js" {
  declare module.exports: $Exports<"pngjs/lib/parser-sync">;
}
declare module "pngjs/lib/parser.js" {
  declare module.exports: $Exports<"pngjs/lib/parser">;
}
declare module "pngjs/lib/png-sync.js" {
  declare module.exports: $Exports<"pngjs/lib/png-sync">;
}
declare module "pngjs/lib/png.js" {
  declare module.exports: $Exports<"pngjs/lib/png">;
}
declare module "pngjs/lib/sync-inflate.js" {
  declare module.exports: $Exports<"pngjs/lib/sync-inflate">;
}
declare module "pngjs/lib/sync-reader.js" {
  declare module.exports: $Exports<"pngjs/lib/sync-reader">;
}
